# Generated by Django 5.2.17 on 2026-10-08 – v1.13.0 EmployeeProfile (side tables, no dependencies)

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BankExtra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bank_detail_id",
                    models.IntegerField(
                        help_text="EmpManagement.EmployeeBankDetail", unique=True
                    ),
                ),
                ("employee_id", models.IntegerField(db_index=True)),
                (
                    "wps_agent",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="WPS agent / exchange house routing (agent ID)",
                        max_length=60,
                    ),
                ),
                (
                    "payment_mode",
                    models.CharField(
                        choices=[
                            ("wps", "WPS (salary transfer)"),
                            ("bank_transfer", "Bank transfer (non-WPS)"),
                            ("cash", "Cash"),
                            ("cheque", "Cheque"),
                        ],
                        default="wps",
                        max_length=14,
                    ),
                ),
                ("is_primary", models.BooleanField(default=False)),
                ("effective_from", models.DateField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="DependentExtra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "family_id",
                    models.IntegerField(
                        help_text="EmpManagement.emp_family", unique=True
                    ),
                ),
                ("employee_id", models.IntegerField(db_index=True)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                        default="",
                        max_length=1,
                    ),
                ),
                (
                    "nationality_id",
                    models.IntegerField(
                        blank=True, help_text="Core.Nationality", null=True
                    ),
                ),
                (
                    "passport_no",
                    models.CharField(blank=True, default="", max_length=12),
                ),
                ("passport_expiry_date", models.DateField(blank=True, null=True)),
                (
                    "emirates_id",
                    models.CharField(blank=True, default="", max_length=18),
                ),
                ("emirates_id_expiry_date", models.DateField(blank=True, null=True)),
                (
                    "visa_number",
                    models.CharField(blank=True, default="", max_length=30),
                ),
                ("visa_expiry_date", models.DateField(blank=True, null=True)),
                ("insured", models.BooleanField(default=False)),
                ("visa_sponsored", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="EmergencyContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("employee_id", models.IntegerField(db_index=True)),
                ("name", models.CharField(max_length=120)),
                ("relation", models.CharField(max_length=40)),
                ("mobile", models.CharField(max_length=24)),
                ("alt_phone", models.CharField(blank=True, default="", max_length=24)),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                ("address", models.CharField(blank=True, default="", max_length=255)),
                ("is_primary", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["employee_id", "-is_primary", "id"],
            },
        ),
        migrations.CreateModel(
            name="EmployeeCodeSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "branch_id",
                    models.IntegerField(
                        blank=True,
                        help_text="OrganisationManager.brnch_mstr; empty = company default",
                        null=True,
                        unique=True,
                    ),
                ),
                ("prefix", models.CharField(blank=True, default="", max_length=20)),
                ("next_number", models.PositiveIntegerField(default=1)),
                ("padding", models.PositiveSmallIntegerField(default=4)),
                ("enabled", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("updated_by_id", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "ordering": ["branch_id"],
            },
        ),
        migrations.CreateModel(
            name="EmployeeIdentity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("employee_id", models.IntegerField(unique=True)),
                (
                    "arabic_name",
                    models.CharField(blank=True, default="", max_length=150),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Mr", "Mr"),
                            ("Mrs", "Mrs"),
                            ("Ms", "Ms"),
                            ("Miss", "Miss"),
                            ("Dr", "Dr"),
                            ("Eng", "Eng"),
                            ("Prof", "Prof"),
                        ],
                        default="",
                        max_length=10,
                    ),
                ),
                (
                    "preferred_name",
                    models.CharField(blank=True, default="", max_length=80),
                ),
                (
                    "passport_no",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=12
                    ),
                ),
                ("passport_issue_date", models.DateField(blank=True, null=True)),
                ("passport_expiry_date", models.DateField(blank=True, null=True)),
                (
                    "passport_place_of_issue",
                    models.CharField(blank=True, default="", max_length=80),
                ),
                (
                    "passport_country_id",
                    models.IntegerField(
                        blank=True, help_text="Core.cntry_mstr", null=True
                    ),
                ),
                (
                    "visa_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("employment", "Employment visa"),
                            ("residence", "Residence (family sponsored)"),
                            ("investor", "Investor / partner"),
                            ("golden", "Golden visa"),
                            ("green", "Green visa"),
                            ("freelance", "Freelance permit"),
                            ("mission", "Mission / work permit"),
                            ("visit", "Visit visa"),
                            ("national", "UAE / GCC national (no visa)"),
                            ("other", "Other"),
                        ],
                        default="",
                        max_length=12,
                    ),
                ),
                (
                    "visa_number",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="entry permit / residence number",
                        max_length=30,
                    ),
                ),
                (
                    "visa_uid",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="UID number (digits)",
                        max_length=15,
                    ),
                ),
                (
                    "visa_file_no",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="file number, e.g. 201/2024/1234567",
                        max_length=30,
                    ),
                ),
                ("visa_issue_date", models.DateField(blank=True, null=True)),
                ("visa_expiry_date", models.DateField(blank=True, null=True)),
                (
                    "visa_sponsor",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "emirates_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="784-YYYY-NNNNNNN-N",
                        max_length=18,
                    ),
                ),
                ("emirates_id_issue_date", models.DateField(blank=True, null=True)),
                ("emirates_id_expiry_date", models.DateField(blank=True, null=True)),
                (
                    "labour_card_no",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=20
                    ),
                ),
                ("labour_card_issue_date", models.DateField(blank=True, null=True)),
                ("labour_card_expiry_date", models.DateField(blank=True, null=True)),
                (
                    "work_permit_no",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("work_permit_expiry_date", models.DateField(blank=True, null=True)),
                (
                    "mohre_contract_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("limited", "Limited (fixed term)"),
                            ("unlimited", "Unlimited"),
                        ],
                        default="",
                        max_length=10,
                    ),
                ),
                (
                    "mohre_contract_no",
                    models.CharField(blank=True, default="", max_length=30),
                ),
                ("mohre_contract_start", models.DateField(blank=True, null=True)),
                ("mohre_contract_end", models.DateField(blank=True, null=True)),
                (
                    "insurance_provider",
                    models.CharField(blank=True, default="", max_length=80),
                ),
                (
                    "insurance_card_no",
                    models.CharField(blank=True, default="", max_length=40),
                ),
                ("insurance_expiry_date", models.DateField(blank=True, null=True)),
                (
                    "doc_links",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="{passport|visa|emirates_id|labour_card: Emp_Documents id}",
                    ),
                ),
                (
                    "doc_problems",
                    models.JSONField(
                        blank=True, default=dict, help_text="last sync problem per kind"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("updated_by_id", models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="EmploymentInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("employee_id", models.IntegerField(unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("probation", "On probation"),
                            ("on_notice", "On notice"),
                            ("left", "Left"),
                            ("terminated", "Terminated"),
                            ("absconded", "Absconded"),
                            ("retired", "Retired"),
                        ],
                        default="active",
                        max_length=12,
                    ),
                ),
                ("probation_end_date", models.DateField(blank=True, null=True)),
                (
                    "probation_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("on_probation", "On probation"),
                            ("extended", "Extended"),
                            ("confirmed", "Confirmed"),
                            ("failed", "Not confirmed (failed)"),
                        ],
                        default="",
                        max_length=12,
                    ),
                ),
                (
                    "probation_days",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="days the end date was worked out from",
                        null=True,
                    ),
                ),
                (
                    "probation_source",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="employment_type | branch | manual",
                        max_length=20,
                    ),
                ),
                ("confirmed_on", models.DateField(blank=True, null=True)),
                ("failed_on", models.DateField(blank=True, null=True)),
                ("decided_by_id", models.IntegerField(blank=True, null=True)),
                (
                    "decision_note",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("date_of_leaving", models.DateField(blank=True, null=True)),
                (
                    "leaving_reason",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "leaving_source",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="resignation:<id> | eos:<id> | probation | manual",
                        max_length=40,
                    ),
                ),
                ("last_reminded_on", models.DateField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("updated_by_id", models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ProbationExtension",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("employee_id", models.IntegerField(db_index=True)),
                (
                    "from_date",
                    models.DateField(help_text="end date before the extension"),
                ),
                ("to_date", models.DateField(help_text="new end date")),
                ("reason", models.CharField(max_length=255)),
                (
                    "decided_by",
                    models.IntegerField(blank=True, help_text="user id", null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["employee_id", "created_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="QualificationExtra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "qualification_id",
                    models.IntegerField(
                        help_text="EmpManagement.EmpQualification", unique=True
                    ),
                ),
                ("employee_id", models.IntegerField(db_index=True)),
                ("grade", models.CharField(blank=True, default="", max_length=40)),
                (
                    "country_id",
                    models.IntegerField(
                        blank=True, help_text="Core.cntry_mstr", null=True
                    ),
                ),
                (
                    "attested",
                    models.BooleanField(
                        default=False,
                        help_text="attested by the UAE Ministry of Foreign Affairs",
                    ),
                ),
                ("attestation_date", models.DateField(blank=True, null=True)),
                (
                    "equivalency",
                    models.BooleanField(
                        default=False,
                        help_text="equivalency certificate from the Ministry of Education",
                    ),
                ),
                (
                    "attachment",
                    models.FileField(
                        blank=True, null=True, upload_to="qualification_attestation/"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
