# Generated by Django 5.2.17 on 2026-10-08 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("EmployeeProfile", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeeidentity",
            name="driving_licence_categories",
            field=models.CharField(
                blank=True,
                default="",
                help_text="e.g. Light vehicle, Motorcycle",
                max_length=120,
            ),
        ),
        migrations.AddField(
            model_name="employeeidentity",
            name="driving_licence_emirate",
            field=models.CharField(
                blank=True,
                choices=[
                    ("abu_dhabi", "Abu Dhabi"),
                    ("dubai", "Dubai"),
                    ("sharjah", "Sharjah"),
                    ("ajman", "Ajman"),
                    ("umm_al_quwain", "Umm Al Quwain"),
                    ("ras_al_khaimah", "Ras Al Khaimah"),
                    ("fujairah", "Fujairah"),
                    ("other", "Other"),
                ],
                default="",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="employeeidentity",
            name="driving_licence_expiry_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="employeeidentity",
            name="driving_licence_issue_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="employeeidentity",
            name="driving_licence_no",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="employeeidentity",
            name="place_of_birth",
            field=models.CharField(blank=True, default="", max_length=80),
        ),
        migrations.AlterField(
            model_name="employeeidentity",
            name="doc_links",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="{passport|visa|emirates_id|labour_card|driving_licence: Emp_Documents id}",
            ),
        ),
    ]
