# Generated by Django 5.2.17 on 2026-10-06 08:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Core", "0001_initial"),
        ("EmpManagement", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("serial_number", models.CharField(max_length=100, unique=True)),
                ("model", models.CharField(blank=True, max_length=100)),
                ("purchase_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("assigned", "Assigned"),
                            ("maintenance", "Under Maintenance"),
                            ("disposed", "Disposed"),
                        ],
                        default="available",
                        max_length=20,
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("healthy", "Healthy"),
                            ("minor_damage", "Minor Damage"),
                            ("major_damage", "Major Damage"),
                        ],
                        default="healthy",
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AssetApprovalWorkflow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "approval_type",
                    models.CharField(
                        choices=[
                            ("no_approval", "No Approval"),
                            ("reporting_manager", "Reporting Manager"),
                            ("multi_approval", "Multi Approval"),
                        ],
                        default="no_approval",
                        max_length=30,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AssetCustomField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("custom_field", models.CharField(max_length=100, unique=True)),
                (
                    "data_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("dropdown", "DropdownField"),
                            ("radio", "RadioButtonField"),
                            ("date", "DateField"),
                            ("text", "TextField"),
                            ("checkbox", "CheckboxField"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("dropdown_values", models.JSONField(blank=True, null=True)),
                ("radio_values", models.JSONField(blank=True, null=True)),
                ("checkbox_values", models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="AssetReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_name", models.CharField(max_length=100, null=True, unique=True)),
                (
                    "report_data",
                    models.FileField(blank=True, null=True, upload_to="asset_report/"),
                ),
            ],
            options={
                "permissions": (("asset_export_report", "Can export asset report"),),
            },
        ),
        migrations.CreateModel(
            name="AssetTransactionReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_name", models.CharField(max_length=100, null=True, unique=True)),
                (
                    "report_data",
                    models.FileField(
                        blank=True, null=True, upload_to="asset_transaction_report/"
                    ),
                ),
            ],
            options={
                "permissions": (
                    (
                        "asset_transaction_export_report",
                        "Can export asset transaction report",
                    ),
                ),
            },
        ),
        migrations.CreateModel(
            name="AssetType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "min_approvals_required",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Minimum number of approvals required to complete the request",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField()),
                ("send_email", models.BooleanField(default=True)),
                ("is_sticky", models.BooleanField(default=False)),
                ("schedule_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "attachment",
                    models.FileField(blank=True, null=True, upload_to="announcements/"),
                ),
                ("allow_comments", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "specific_employees",
                    models.ManyToManyField(
                        blank=True,
                        related_name="employee_announcements",
                        to="EmpManagement.emp_master",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AnnouncementComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comment", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "announcement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="announcement_comments",
                        to="OrganisationManager.announcement",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="EmpManagement.emp_master",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AssetAllocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assigned_date", models.DateField(blank=True, null=True)),
                ("returned_date", models.DateField(blank=True, null=True)),
                (
                    "return_condition",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("healthy", "Healthy"),
                            ("minor_damage", "Minor Damage"),
                            ("major_damage", "Major Damage"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allocations",
                        to="OrganisationManager.asset",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allocations",
                        to="EmpManagement.emp_master",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AssetApprovalLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("level", models.IntegerField()),
                ("role", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "escalate_after_days",
                    models.PositiveIntegerField(
                        default=0, help_text="Escalate after X days if pending"
                    ),
                ),
                (
                    "escalate_after_hours",
                    models.PositiveIntegerField(
                        default=0, help_text="Escalate after X hours if pending"
                    ),
                ),
                (
                    "escalate_after_minutes",
                    models.PositiveIntegerField(
                        default=0, help_text="Escalate after X minutes if pending"
                    ),
                ),
                (
                    "approver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "escalate_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="asset_escalated_levels",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asset_levels",
                        to="OrganisationManager.assetapprovalworkflow",
                    ),
                ),
            ],
            options={
                "permissions": (
                    ("add_asset_escalation", "Can add Escalation"),
                    ("view_asset_escalation", "Can view Escalation"),
                    ("change_asset_escalation", "Can change Escalation"),
                    ("export_asset_escalation", "Can export Escalation"),
                    ("delete_asset_escalation", "Can delete Escalation"),
                ),
            },
        ),
        migrations.CreateModel(
            name="AssetCustomFieldValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("field_value", models.TextField(blank=True, null=True)),
                (
                    "asset",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_field_values",
                        to="OrganisationManager.asset",
                    ),
                ),
                (
                    "custom_field",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="field_values",
                        to="OrganisationManager.assetcustomfield",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AssetNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_read", models.BooleanField(default=False)),
                ("is_deligate", models.BooleanField(default=False)),
                (
                    "deligate_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asset_deligated_notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "recipient_employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="EmpManagement.emp_master",
                    ),
                ),
                (
                    "recipient_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AssetRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reason", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("request_date", models.DateTimeField(auto_now=True)),
                (
                    "document_number",
                    models.CharField(blank=True, max_length=50, unique=True),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asset_requests",
                        to="EmpManagement.emp_master",
                    ),
                ),
                (
                    "requested_asset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="OrganisationManager.asset",
                    ),
                ),
                (
                    "asset_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="OrganisationManager.assettype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AssetApproval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role", models.CharField(blank=True, max_length=50, null=True)),
                ("level", models.IntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Approved", "Approved"),
                            ("Rejected", "Rejected"),
                            ("Escalated", "Escalated"),
                        ],
                        default="Pending",
                        max_length=20,
                    ),
                ),
                ("note", models.TextField(blank=True, null=True)),
                ("is_deligate", models.BooleanField(default=False)),
                ("deligate_response", models.TextField(blank=True, null=True)),
                ("escalated", models.BooleanField(default=False)),
                ("escalated_at", models.DateTimeField(blank=True, null=True)),
                ("is_escalation", models.BooleanField(default=False)),
                ("created_at", models.DateField(auto_now_add=True)),
                ("updated_at", models.DateField(auto_now=True)),
                (
                    "approver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deligate_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="asset_deligations_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "asset_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approvals",
                        to="OrganisationManager.assetrequest",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="assetcustomfield",
            name="asset_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="custom_fields",
                to="OrganisationManager.assettype",
            ),
        ),
        migrations.AddField(
            model_name="assetapprovalworkflow",
            name="asset_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="approval_levels",
                to="OrganisationManager.assettype",
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="asset_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assets",
                to="OrganisationManager.assettype",
            ),
        ),
        migrations.CreateModel(
            name="brnch_mstr",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("branch_name", models.CharField(max_length=100)),
                ("branch_code", models.CharField(max_length=50, unique=True)),
                ("branch_logo", models.ImageField(null=True, upload_to="")),
                ("probation_period_days", models.IntegerField(default=0)),
                ("br_start_date", models.DateField(null=True)),
                ("br_is_active", models.BooleanField(default=True)),
                ("br_city", models.CharField(blank=True, max_length=50, null=True)),
                ("br_pincode", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "br_branch_nmbr_1",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "br_branch_nmbr_2",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "br_branch_mail",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("branch_address", models.TextField(blank=True, null=True)),
                ("br_created_at", models.DateTimeField(auto_now_add=True)),
                ("br_updated_at", models.DateTimeField(auto_now=True)),
                (
                    "br_country",
                    models.ForeignKey(
                        default="1",
                        null=True,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        to="Core.cntry_mstr",
                    ),
                ),
                (
                    "br_created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "br_state_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Core.state_mstr",
                    ),
                ),
                (
                    "br_updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BranchGeoFence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "location_type",
                    models.CharField(
                        choices=[
                            ("office", "Office"),
                            ("home", "Home"),
                            ("remote", "Remote Site"),
                            ("client", "Client Site"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "location_name",
                    models.CharField(
                        help_text="e.g. Main Gate, Warehouse Entry", max_length=200
                    ),
                ),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                (
                    "radius",
                    models.IntegerField(
                        default=50, help_text="Geofence radius in meters"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ManyToManyField(
                        blank=True,
                        related_name="allowed_geolocations",
                        to="EmpManagement.emp_master",
                    ),
                ),
                (
                    "branch",
                    models.ManyToManyField(
                        blank=True,
                        related_name="geo_fences",
                        to="OrganisationManager.brnch_mstr",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="assettype",
            name="branch",
            field=models.ManyToManyField(
                blank=True, to="OrganisationManager.brnch_mstr"
            ),
        ),
        migrations.AddField(
            model_name="assetrequest",
            name="branch",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="OrganisationManager.brnch_mstr",
            ),
        ),
        migrations.AddField(
            model_name="assetapprovalworkflow",
            name="branch",
            field=models.ManyToManyField(
                blank=True, to="OrganisationManager.brnch_mstr"
            ),
        ),
        migrations.AddField(
            model_name="announcement",
            name="branches",
            field=models.ManyToManyField(
                blank=True,
                related_name="branch_announcements",
                to="OrganisationManager.brnch_mstr",
            ),
        ),
        migrations.CreateModel(
            name="ctgry_master",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ctgry_title", models.CharField(max_length=50)),
                (
                    "ctgry_code",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                (
                    "ctgry_description",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("ctgry_created_at", models.DateTimeField(auto_now_add=True)),
                ("ctgry_updated_at", models.DateTimeField(auto_now=True)),
                ("ctgry_is_active", models.BooleanField(default=True)),
                (
                    "branch",
                    models.ManyToManyField(
                        blank=True,
                        related_name="ctgry_branches",
                        to="OrganisationManager.brnch_mstr",
                    ),
                ),
                (
                    "ctgry_created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ctgry_updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "permissions": (("import_ctgry_master", "Can import category master"),),
            },
        ),
        migrations.AddField(
            model_name="announcement",
            name="category",
            field=models.ManyToManyField(
                blank=True, null=True, to="OrganisationManager.ctgry_master"
            ),
        ),
        migrations.CreateModel(
            name="dept_master",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dept_name", models.CharField(max_length=50)),
                (
                    "dept_code",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                (
                    "dept_description",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("dept_created_at", models.DateTimeField(auto_now_add=True)),
                ("dept_updated_at", models.DateTimeField(auto_now=True)),
                ("dept_is_active", models.BooleanField(default=True)),
                (
                    "branch",
                    models.ManyToManyField(
                        blank=True,
                        related_name="dept_branches",
                        to="OrganisationManager.brnch_mstr",
                    ),
                ),
                (
                    "dept_created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dept_updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "permissions": (
                    ("view_dept_report", "Can view department report"),
                    ("export_dept_report", "Can export department report"),
                    ("delete_dept_report", "Can delete department report"),
                    ("import_dept_master", "Can import department master"),
                ),
            },
        ),
        migrations.AddField(
            model_name="announcement",
            name="department",
            field=models.ManyToManyField(
                blank=True, null=True, to="OrganisationManager.dept_master"
            ),
        ),
        migrations.CreateModel(
            name="desgntn_master",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("desgntn_job_title", models.CharField(max_length=50)),
                (
                    "desgntn_code",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                (
                    "desgntn_description",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("desgntn_created_at", models.DateTimeField(auto_now_add=True)),
                ("desgntn_updated_at", models.DateTimeField(auto_now=True)),
                ("desgntn_is_active", models.BooleanField(default=True)),
                (
                    "branch",
                    models.ManyToManyField(
                        blank=True,
                        related_name="desgntn_branches",
                        to="OrganisationManager.brnch_mstr",
                    ),
                ),
                (
                    "desgntn_created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "desgntn_updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "permissions": (
                    ("view_designtn_report", "Can view designation report"),
                    ("export_designtn_report", "Can export designation report"),
                    ("delete_designtn_report", "Can delete designation report"),
                    ("import_designtn_master", "Can import department master"),
                ),
            },
        ),
        migrations.CreateModel(
            name="CompanyPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                ("policy_file", models.FileField(upload_to="policies/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "branch",
                    models.ManyToManyField(
                        blank=True,
                        related_name="policies",
                        to="OrganisationManager.brnch_mstr",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "specific_users",
                    models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="policies",
                        to="OrganisationManager.ctgry_master",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="policies",
                        to="OrganisationManager.dept_master",
                    ),
                ),
                (
                    "designation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="policies",
                        to="OrganisationManager.desgntn_master",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AssetEmailTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "template_type",
                    models.CharField(
                        choices=[
                            ("asset_created", "Asset Created"),
                            ("asset_approved", "Asset Approved"),
                            ("asset_rejected", "Asset Rejected"),
                        ],
                        max_length=50,
                    ),
                ),
                ("subject", models.CharField(max_length=255)),
                ("body", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "branch",
                    models.ManyToManyField(
                        blank=True, to="OrganisationManager.brnch_mstr"
                    ),
                ),
                (
                    "Category",
                    models.ManyToManyField(
                        blank=True, to="OrganisationManager.ctgry_master"
                    ),
                ),
                (
                    "Department",
                    models.ManyToManyField(
                        blank=True, to="OrganisationManager.dept_master"
                    ),
                ),
                (
                    "Designation",
                    models.ManyToManyField(
                        blank=True, to="OrganisationManager.desgntn_master"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="announcement",
            name="designation",
            field=models.ManyToManyField(
                blank=True, null=True, to="OrganisationManager.desgntn_master"
            ),
        ),
        migrations.CreateModel(
            name="FiscalYear",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "branch_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="OrganisationManager.brnch_mstr",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Folder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subfolders",
                        to="OrganisationManager.folder",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "unique_together": {("name", "parent")},
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("file", models.FileField(upload_to="documents/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "folder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="OrganisationManager.folder",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GratuityTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "minimum_value",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Minimum years of service",
                        max_digits=5,
                    ),
                ),
                (
                    "maximum_value",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Maximum years of service",
                        max_digits=5,
                    ),
                ),
                (
                    "resignation_days",
                    models.PositiveIntegerField(
                        help_text="Gratuity days for resignation"
                    ),
                ),
                (
                    "termination_days",
                    models.PositiveIntegerField(
                        help_text="Gratuity days for termination"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Is this range active?"
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("minimum_value__lt", models.F("maximum_value")),
                            ("maximum_value__isnull", True),
                            _connector="OR",
                        ),
                        name="valid_range",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="UserBranchAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "branch",
                    models.ManyToManyField(
                        blank=True, to="OrganisationManager.brnch_mstr"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="branch_accesses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AnnouncementView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("viewed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "announcement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="announcement_views",
                        to="OrganisationManager.announcement",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="EmpManagement.emp_master",
                    ),
                ),
            ],
            options={
                "unique_together": {("announcement", "employee")},
            },
        ),
        migrations.CreateModel(
            name="DocumentNumbering",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("general_request", "General Request"),
                            ("leave_request", "Leave Request"),
                            ("advance_salary_request", "Advance Salary Request"),
                            ("air_ticket_request", "Air Ticket Request"),
                            ("loan_request", "Loan Request"),
                            ("asset_request", "Asset Request"),
                            ("document_request", "Document Request"),
                            ("resignation_request", "Resignation Request"),
                            ("lateinearlyout_request", "LateinEarlyout Request"),
                            ("payroll_run", "PayRollRun"),
                        ],
                        max_length=50,
                    ),
                ),
                ("automatic_numbering", models.BooleanField(default=True)),
                ("prefix", models.CharField(max_length=50)),
                ("suffix", models.CharField(blank=True, max_length=50, null=True)),
                ("current_number", models.IntegerField(default=0)),
                ("total_length", models.IntegerField(default=10)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "branch_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="OrganisationManager.brnch_mstr",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="document_numbering_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_numbering_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("branch_id", "type"), name="unique_type_per_branch"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="FiscalPeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("period_number", models.PositiveIntegerField()),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fiscal_periods",
                        to="OrganisationManager.brnch_mstr",
                    ),
                ),
                (
                    "fiscal_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="OrganisationManager.fiscalyear",
                    ),
                ),
            ],
            options={
                "unique_together": {("fiscal_year", "period_number")},
            },
        ),
    ]
