# Generated by Django 5.2.17 on 2026-10-06 21:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model", models.CharField(db_index=True, max_length=120)),
                ("object_id", models.CharField(db_index=True, max_length=64)),
                ("record_label", models.CharField(blank=True, max_length=255)),
                ("screen", models.CharField(blank=True, max_length=255)),
                ("page", models.CharField(blank=True, max_length=255)),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("todo", "To-do"),
                            ("call", "Call"),
                            ("meeting", "Meeting"),
                            ("email", "E-mail"),
                            ("document", "Upload document"),
                            ("approval", "Approval"),
                            ("follow_up", "Follow-up"),
                        ],
                        default="todo",
                        max_length=20,
                    ),
                ),
                ("summary", models.CharField(max_length=255)),
                ("note", models.TextField(blank=True)),
                ("due_date", models.DateField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("done", "Done"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=10,
                    ),
                ),
                ("done_at", models.DateTimeField(blank=True, null=True)),
                ("feedback", models.TextField(blank=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "done_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["due_date", "id"],
            },
        ),
        migrations.CreateModel(
            name="Attachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model", models.CharField(db_index=True, max_length=120)),
                ("object_id", models.CharField(db_index=True, max_length=64)),
                ("file", models.FileField(upload_to="attachments/%Y/%m/")),
                ("name", models.CharField(max_length=255)),
                ("size", models.PositiveIntegerField(default=0)),
                ("mime", models.CharField(blank=True, max_length=120)),
                ("field", models.CharField(blank=True, max_length=100)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="FieldDef",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("screen", models.CharField(db_index=True, max_length=255)),
                ("model", models.CharField(db_index=True, max_length=120)),
                ("name", models.SlugField(max_length=100)),
                ("label", models.CharField(max_length=150)),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("textarea", "Long text"),
                            ("integer", "Whole number"),
                            ("decimal", "Decimal number"),
                            ("currency", "Amount (AED)"),
                            ("percent", "Percentage"),
                            ("date", "Date"),
                            ("datetime", "Date and time"),
                            ("time", "Time"),
                            ("checkbox", "Yes / No"),
                            ("dropdown", "Dropdown"),
                            ("multiselect", "Multi-select"),
                            ("radio", "Radio buttons"),
                            ("email", "E-mail"),
                            ("phone", "Phone"),
                            ("url", "Web link"),
                            ("file", "File"),
                            ("employee", "Employee"),
                            ("rating", "Rating (1–5)"),
                            ("color", "Colour"),
                        ],
                        default="text",
                        max_length=20,
                    ),
                ),
                ("options", models.JSONField(blank=True, default=list)),
                ("required", models.BooleanField(default=False)),
                ("section", models.CharField(blank=True, max_length=100)),
                ("order", models.IntegerField(default=0)),
                ("help_text", models.CharField(blank=True, max_length=255)),
                ("default", models.CharField(blank=True, max_length=255)),
                ("show_in_list", models.BooleanField(default=True)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["section", "order", "id"],
                "unique_together": {("model", "name")},
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model", models.CharField(db_index=True, max_length=120)),
                ("object_id", models.CharField(db_index=True, max_length=64)),
                ("body", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("edited_at", models.DateTimeField(blank=True, null=True)),
                (
                    "attachments",
                    models.ManyToManyField(
                        blank=True, related_name="messages", to="Chatter.attachment"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="DashboardLayout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dashboard", models.CharField(default="main", max_length=40)),
                ("hidden", models.JSONField(blank=True, default=list)),
                ("order", models.JSONField(blank=True, default=list)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "dashboard")},
            },
        ),
        migrations.CreateModel(
            name="FieldValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.CharField(db_index=True, max_length=64)),
                ("value", models.JSONField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="values",
                        to="Chatter.fielddef",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("field", "object_id")},
            },
        ),
        migrations.CreateModel(
            name="ListLayout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=255)),
                ("data", models.JSONField(blank=True, default=dict)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "key")},
            },
        ),
        migrations.CreateModel(
            name="RecordLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model", models.CharField(db_index=True, max_length=120)),
                ("object_id", models.CharField(db_index=True, max_length=64)),
                ("record_label", models.CharField(blank=True, max_length=255)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("updated", "Updated"),
                            ("deleted", "Deleted"),
                        ],
                        max_length=10,
                    ),
                ),
                ("changes", models.JSONField(blank=True, default=dict)),
                ("user_name", models.CharField(blank=True, max_length=150)),
                ("at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("ip", models.CharField(blank=True, max_length=64)),
                ("path", models.CharField(blank=True, max_length=255)),
                ("method", models.CharField(blank=True, max_length=10)),
                ("agent", models.CharField(blank=True, max_length=255)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["model", "object_id", "-at"],
                        name="Chatter_rec_model_1aeb78_idx",
                    )
                ],
            },
        ),
    ]
