# Generated by Django 5.2.17 on 2026-10-07 16:16

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CostRateSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hours_per_day",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("8"), max_digits=4
                    ),
                ),
                (
                    "include_allowance_categories",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Payroll categories of additions counted as fixed pay (empty = every fixed addition except variable pay)",
                    ),
                ),
                (
                    "overhead_percent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProjectFinance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "project_id",
                    models.IntegerField(
                        help_text="ProjectManagement.Project id", unique=True
                    ),
                ),
                (
                    "customer_name",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "contract_value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "budget_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Cost budget",
                        max_digits=14,
                    ),
                ),
                (
                    "budget_hours",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("currency", models.CharField(default="AED", max_length=3)),
                (
                    "billing_type",
                    models.CharField(
                        choices=[
                            ("fixed", "Fixed price"),
                            ("time_and_material", "Time & material"),
                            ("non_billable", "Non-billable"),
                        ],
                        default="time_and_material",
                        max_length=20,
                    ),
                ),
                (
                    "default_bill_rate",
                    models.DecimalField(
                        decimal_places=2, default=0, help_text="Per hour", max_digits=10
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["project_id"],
            },
        ),
        migrations.CreateModel(
            name="TaskPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task_id", models.IntegerField(unique=True)),
                (
                    "planned_hours",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("billable", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="TimesheetExtra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timesheet_id", models.IntegerField(unique=True)),
                (
                    "hours",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                ("billable", models.BooleanField(default=True)),
                ("start_at", models.DateTimeField(blank=True, null=True)),
                ("stop_at", models.DateTimeField(blank=True, null=True)),
                ("running", models.BooleanField(db_index=True, default=False)),
                (
                    "approval_status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=12,
                    ),
                ),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("approver_user_id", models.IntegerField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True, default="")),
                (
                    "cost_rate",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "cost_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "bill_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "bill_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "corrected_from",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Earlier versions of a rejected entry",
                    ),
                ),
            ],
            options={
                "permissions": (
                    ("approve_timesheetextra", "Can approve any timesheet entry"),
                ),
            },
        ),
        migrations.CreateModel(
            name="MemberRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("project_id", models.IntegerField(db_index=True)),
                ("employee_id", models.IntegerField(db_index=True)),
                ("role", models.CharField(blank=True, default="", max_length=100)),
                (
                    "bill_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Per hour; empty = project default",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "cost_rate_override",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Per hour; empty = from the salary structure",
                        max_digits=10,
                        null=True,
                    ),
                ),
            ],
            options={
                "ordering": ["project_id", "employee_id"],
                "unique_together": {("project_id", "employee_id")},
            },
        ),
    ]
