# Generated by Django 5.2.17 on 2026-10-07 20:41

import AttendancePlus.models
import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AttendanceRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("company", "Whole company"),
                            ("branch", "Branch"),
                            ("department", "Department"),
                            ("category", "Category"),
                            ("employee", "Employee"),
                        ],
                        default="company",
                        max_length=12,
                    ),
                ),
                (
                    "branch_id",
                    models.IntegerField(blank=True, db_index=True, null=True),
                ),
                ("department_id", models.IntegerField(blank=True, null=True)),
                ("category_id", models.IntegerField(blank=True, null=True)),
                ("employee_id", models.IntegerField(blank=True, null=True)),
                ("priority", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("default_start", models.TimeField(blank=True, null=True)),
                ("default_end", models.TimeField(blank=True, null=True)),
                ("grace_in_minutes", models.PositiveIntegerField(default=0)),
                (
                    "late_from",
                    models.CharField(
                        choices=[
                            ("shift_start", "Shift start"),
                            ("grace_end", "End of grace period"),
                        ],
                        default="shift_start",
                        max_length=12,
                    ),
                ),
                ("late_tolerance_minutes", models.PositiveIntegerField(default=0)),
                (
                    "late_beyond_action",
                    models.CharField(
                        choices=[
                            ("none", "Only flag"),
                            ("half_day", "Half day"),
                            ("absent", "Absent"),
                        ],
                        default="half_day",
                        max_length=10,
                    ),
                ),
                ("late_policy_id", models.IntegerField(blank=True, null=True)),
                ("grace_out_minutes", models.PositiveIntegerField(default=0)),
                ("early_tolerance_minutes", models.PositiveIntegerField(default=0)),
                (
                    "early_beyond_action",
                    models.CharField(
                        choices=[
                            ("none", "Only flag"),
                            ("half_day", "Half day"),
                            ("absent", "Absent"),
                        ],
                        default="half_day",
                        max_length=10,
                    ),
                ),
                ("early_policy_id", models.IntegerField(blank=True, null=True)),
                (
                    "min_hours_full_day",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "min_hours_half_day",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "max_hours",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "max_hours_action",
                    models.CharField(
                        choices=[("cap", "Cap the hours"), ("flag", "Only flag")],
                        default="cap",
                        max_length=6,
                    ),
                ),
                ("ot_enabled", models.BooleanField(default=True)),
                (
                    "ot_basis",
                    models.CharField(
                        choices=[
                            ("shift", "After shift hours"),
                            ("daily", "After daily threshold"),
                        ],
                        default="shift",
                        max_length=10,
                    ),
                ),
                ("ot_after_minutes", models.PositiveIntegerField(default=0)),
                (
                    "ot_daily_threshold_hours",
                    models.DecimalField(decimal_places=2, default=8, max_digits=5),
                ),
                (
                    "ot_weekly_threshold_hours",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "ot_monthly_threshold_hours",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                ("ot_min_minutes", models.PositiveIntegerField(default=0)),
                (
                    "ot_max_hours_per_day",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("ot_needs_approval", models.BooleanField(default=True)),
                (
                    "ot_rate_normal",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                (
                    "ot_rate_weekend",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                (
                    "ot_rate_holiday",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                (
                    "ot_rate_night",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                ("night_start", models.TimeField(default=datetime.time(22, 0))),
                ("night_end", models.TimeField(default=datetime.time(6, 0))),
                ("night_min_minutes", models.PositiveIntegerField(default=120)),
                (
                    "cross_midnight",
                    models.CharField(
                        choices=[
                            (
                                "shift_start",
                                "Punch belongs to the day the shift starts",
                            ),
                            ("calendar", "Punch belongs to its calendar day"),
                        ],
                        default="shift_start",
                        max_length=12,
                    ),
                ),
                ("day_change_hour", models.PositiveIntegerField(default=4)),
                ("break_minutes", models.PositiveIntegerField(default=0)),
                ("break_paid", models.BooleanField(default=False)),
                ("auto_deduct_break", models.BooleanField(default=True)),
                (
                    "auto_deduct_after_hours",
                    models.DecimalField(decimal_places=2, default=5, max_digits=4),
                ),
                ("rounding_minutes", models.PositiveIntegerField(default=0)),
                (
                    "rounding_mode",
                    models.CharField(
                        choices=[
                            ("none", "No rounding"),
                            ("nearest", "Nearest"),
                            ("strict", "In up, out down"),
                            ("lenient", "In down, out up"),
                        ],
                        default="none",
                        max_length=10,
                    ),
                ),
                ("mark_absent_if_no_punch", models.BooleanField(default=True)),
                ("exempt_manual_source", models.BooleanField(default=False)),
                ("exempt_category_ids", models.JSONField(blank=True, default=list)),
                ("exempt_employee_ids", models.JSONField(blank=True, default=list)),
                (
                    "missing_punch_after_hours",
                    models.DecimalField(decimal_places=1, default=4, max_digits=4),
                ),
                ("allowed_methods", models.JSONField(blank=True, default=list)),
                ("require_gps", models.BooleanField(default=False)),
                ("require_geofence", models.BooleanField(default=False)),
                ("require_selfie", models.BooleanField(default=False)),
                ("require_ip", models.BooleanField(default=False)),
                ("min_minutes_between_punches", models.PositiveIntegerField(default=1)),
                ("correction_window_days", models.PositiveIntegerField(default=30)),
                ("correction_max_per_month", models.PositiveIntegerField(default=5)),
                ("correction_needs_hr", models.BooleanField(default=True)),
                (
                    "half_day_unpaid_fraction",
                    models.DecimalField(decimal_places=2, default=0.5, max_digits=3),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-priority", "id"],
            },
        ),
        migrations.CreateModel(
            name="CorrectionRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("employee_id", models.IntegerField(db_index=True)),
                (
                    "branch_id",
                    models.IntegerField(blank=True, db_index=True, null=True),
                ),
                ("date", models.DateField()),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("missing_punch", "Missing punch"),
                            ("wrong_time", "Wrong time"),
                            ("forgot", "Forgot to punch"),
                            ("on_duty", "On duty / outside work"),
                            ("wfh", "Work from home"),
                        ],
                        default="missing_punch",
                        max_length=14,
                    ),
                ),
                ("proposed_in", models.DateTimeField(blank=True, null=True)),
                ("proposed_out", models.DateTimeField(blank=True, null=True)),
                ("reason", models.TextField()),
                (
                    "attachment",
                    models.FileField(
                        blank=True, null=True, upload_to="attendance_plus/corrections/"
                    ),
                ),
                ("waive_penalty", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("manager", "Waiting for manager"),
                            ("hr", "Waiting for HR"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="manager",
                        max_length=10,
                    ),
                ),
                ("manager_user_id", models.IntegerField(blank=True, null=True)),
                ("manager_at", models.DateTimeField(blank=True, null=True)),
                ("manager_note", models.TextField(blank=True)),
                ("hr_user_id", models.IntegerField(blank=True, null=True)),
                ("hr_at", models.DateTimeField(blank=True, null=True)),
                ("hr_note", models.TextField(blank=True)),
                ("original", models.JSONField(blank=True, default=dict)),
                ("created_by_id", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("serial_number", models.CharField(max_length=64, unique=True)),
                (
                    "device_type",
                    models.CharField(
                        choices=[
                            ("zkteco", "ZKTeco (ADMS push)"),
                            ("other", "Other (JSON push API)"),
                        ],
                        default="zkteco",
                        max_length=10,
                    ),
                ),
                (
                    "branch_id",
                    models.IntegerField(blank=True, db_index=True, null=True),
                ),
                (
                    "api_key",
                    models.CharField(
                        default=AttendancePlus.models.new_token,
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("use_status_keys", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("last_seen", models.DateTimeField(blank=True, null=True)),
                ("last_ip", models.CharField(blank=True, max_length=64)),
                ("last_stamp", models.CharField(blank=True, max_length=32)),
                ("punches_received", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="EmployeeKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("employee_id", models.IntegerField(unique=True)),
                ("pin_hash", models.CharField(blank=True, max_length=128)),
                ("qr_version", models.PositiveIntegerField(default=1)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="IPRestriction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "branch_id",
                    models.IntegerField(blank=True, db_index=True, null=True),
                ),
                (
                    "cidrs",
                    models.TextField(
                        help_text="One network per line, e.g. 10.0.0.0/24 or 94.200.1.5"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Kiosk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "branch_id",
                    models.IntegerField(blank=True, db_index=True, null=True),
                ),
                (
                    "token",
                    models.CharField(
                        default=AttendancePlus.models.new_token,
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("allow_qr", models.BooleanField(default=True)),
                ("allow_pin", models.BooleanField(default=True)),
                ("allow_face", models.BooleanField(default=False)),
                ("show_site_qr", models.BooleanField(default=False)),
                ("site_qr_seconds", models.PositiveIntegerField(default=30)),
                ("last_seen", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="AttendanceDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("employee_id", models.IntegerField(db_index=True)),
                ("date", models.DateField(db_index=True)),
                (
                    "branch_id",
                    models.IntegerField(blank=True, db_index=True, null=True),
                ),
                ("shift_id", models.IntegerField(blank=True, null=True)),
                ("shift_name", models.CharField(blank=True, max_length=80)),
                ("shift_start", models.DateTimeField(blank=True, null=True)),
                ("shift_end", models.DateTimeField(blank=True, null=True)),
                ("rule_id", models.IntegerField(blank=True, null=True)),
                ("first_in", models.DateTimeField(blank=True, null=True)),
                ("last_out", models.DateTimeField(blank=True, null=True)),
                ("worked_minutes", models.IntegerField(default=0)),
                ("break_minutes", models.IntegerField(default=0)),
                ("late_minutes", models.IntegerField(default=0)),
                ("early_minutes", models.IntegerField(default=0)),
                ("ot_minutes", models.IntegerField(default=0)),
                ("period_ot_minutes", models.IntegerField(default=0)),
                ("ot_type", models.CharField(blank=True, max_length=10)),
                (
                    "ot_rate",
                    models.DecimalField(decimal_places=2, default=1, max_digits=4),
                ),
                ("night_minutes", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("present", "Present"),
                            ("absent", "Absent"),
                            ("half_day", "Half day"),
                            ("leave", "Leave"),
                            ("holiday", "Holiday"),
                            ("weekly_off", "Weekly off"),
                            ("missing_punch", "Missing punch"),
                            ("not_marked", "Not marked yet"),
                        ],
                        default="not_marked",
                        max_length=14,
                    ),
                ),
                ("is_late", models.BooleanField(default=False)),
                ("is_early", models.BooleanField(default=False)),
                ("is_night_shift", models.BooleanField(default=False)),
                ("missing_punch", models.BooleanField(default=False)),
                ("over_max_hours", models.BooleanField(default=False)),
                ("penalty_waived", models.BooleanField(default=False)),
                ("punch_count", models.IntegerField(default=0)),
                ("sources", models.JSONField(blank=True, default=list)),
                ("flags", models.JSONField(blank=True, default=dict)),
                ("notified_missing_at", models.DateTimeField(blank=True, null=True)),
                ("computed_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-date", "employee_id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("employee_id", "date"), name="attplus_day_once"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Punch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("employee_id", models.IntegerField(db_index=True)),
                ("ts", models.DateTimeField(db_index=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("in", "Clock in"),
                            ("out", "Clock out"),
                            ("break_out", "Break start"),
                            ("break_in", "Break end"),
                            ("lunch_out", "Lunch start"),
                            ("lunch_in", "Lunch end"),
                            ("auto", "Automatic (in or out)"),
                        ],
                        default="auto",
                        max_length=10,
                    ),
                ),
                ("resolved_kind", models.CharField(blank=True, max_length=10)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("web", "Web"),
                            ("mobile", "Mobile app"),
                            ("biometric", "Biometric / face"),
                            ("kiosk", "Kiosk"),
                            ("device", "Attendance device"),
                            ("qr", "QR / barcode"),
                            ("import", "Bulk import"),
                            ("correction", "Attendance correction"),
                            ("manual", "Manual entry by HR"),
                        ],
                        default="web",
                        max_length=12,
                    ),
                ),
                ("work_date", models.DateField(blank=True, db_index=True, null=True)),
                ("device_ref", models.CharField(blank=True, max_length=64)),
                ("ip", models.CharField(blank=True, max_length=64)),
                (
                    "lat",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "lng",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=255)),
                ("geofence_ok", models.BooleanField(null=True)),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="attendance_plus/punch/"
                    ),
                ),
                ("verified_by", models.CharField(blank=True, max_length=12)),
                ("is_void", models.BooleanField(default=False)),
                ("void_reason", models.CharField(blank=True, max_length=255)),
                ("note", models.CharField(blank=True, max_length=255)),
                ("created_by_id", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "correction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="punches",
                        to="AttendancePlus.correctionrequest",
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="AttendancePlus.device",
                    ),
                ),
                (
                    "kiosk",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="AttendancePlus.kiosk",
                    ),
                ),
            ],
            options={
                "ordering": ["ts", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("employee_id", "ts"), name="attplus_punch_once"
                    )
                ],
            },
        ),
    ]
