from django.db.models.signals import post_migrate
from django.dispatch import receiver
from django.db import connection

from .models import cntry_mstr, Nationality, ReligionMaster


@receiver(post_migrate)
def create_core_master_data(sender, **kwargs):

    if sender.name != "Core":
        return

    # Only create master data in public schema
    if connection.schema_name != "public":
        return

    # ---------------- COUNTRY ----------------

    countries = [
        "Afghanistan",
        "Albania",
        "Algeria",
        "American Samoa",
        "Andorra",
        "Angola",
        "Anguilla",
        "Antarctica",
        "Antigua and Barbuda",
        "Argentina",
        "Armenia",
        "Aruba",
        "Australia",
        "Austria",
        "Azerbaijan",
        "Bahamas",
        "Bahrain",
        "Bangladesh",
        "Barbados",
        "Belarus",
        "Belgium",
        "Belize",
        "Benin",
        "Bermuda",
        "Bhutan",
        "Bolivia (Plurinational State of)",
        "Bonaire, Sint Eustatius and Saba",
        "Bosnia and Herzegovina",
        "Botswana",
        "Bouvet Island",
        "Brazil",
        "British Indian Ocean Territory",
        "Brunei Darussalam",
        "Bulgaria",
        "Burundi",
        "Cabo Verde",
        "Cambodia",
        "Cameroon",
        "Canada",
        "Cayman Islands",
        "Central African Republic",
        "Chad",
        "Chile",
        "China",
        "Christmas Island",
        "Cocos (Keeling) Islands",
        "Colombia",
        "Comoros",
        "Congo (Republic of the)",
        "Congo (Democratic Republic of the)",
        "Cook Islands",
        "Costa Rica",
        "CÃ´te d'Ivoire",
        "Croatia",
        "Cuba",
        "CuraÃ§ao",
        "Cyprus",
        "Czech Republic",
        "Denmark",
        "Djibouti",
        "Dominica",
        "Dominican Republic",
        "Ecuador",
        "Egypt",
        "El Salvador",
        "Equatorial Guinea",
        "Eritrea",
        "Estonia",
        "Ethiopia",
        "Falkland Islands (Malvinas)",
        "Faroe Islands",
        "Fiji",
        "Finland",
        "France",
        "French Guiana",
        "French Polynesia",
        "French Southern Territories",
        "Gabon",
        "Gambia",
        "Georgia",
        "Germany",
        "Ghana",
        "Gibraltar",
        "Greece",
        "Greenland",
        "Grenada",
        "Guadeloupe",
        "Guam",
        "Guatemala",
        "Guernsey",
        "Guinea",
        "Guinea-Bissau",
        "Guyana",
        "Haiti",
        "Heard Island and McDonald Islands",
        "Vatican City State",
        "Honduras",
        "Hong Kong",
        "Hungary",
        "Iceland",
        "India",
        "Indonesia",
        "Iran",
        "Iraq",
        "Ireland",
        "Isle of Man",
        "Israel",
        "Italy",
        "Jamaica",
        "Japan",
        "Jersey",
        "Jordan",
        "Kazakhstan",
        "Kenya",
        "Kiribati",
        "Korea (Democratic People's Republic of)",
        "Korea (Republic of)",
        "Kuwait",
        "Kyrgyzstan",
        "Lao People's Democratic Republic",
        "Latvia",
        "Lebanon",
        "Lesotho",
        "Liberia",
        "Libya",
        "Liechtenstein",
        "Lithuania",
        "Luxembourg",
        "Macao",
        "Macedonia (the former Yugoslav Republic of)",
        "Madagascar",
        "Malawi",
        "Malaysia",
        "Maldives",
        "Mali",
        "Malta",
        "Marshall Islands",
        "Martinique",
        "Mauritania",
        "Mauritius",
        "Mayotte",
        "Mexico",
        "Micronesia (Federated States of)",
        "Moldova (Republic of)",
        "Mongolia",
        "Montenegro",
        "Montserrat",
        "Morocco",
        "Mozambique",
        "Myanmar",
        "Namibia",
        "Nauru",
        "Nepal",
        "Netherlands",
        "New Caledonia",
        "New Zealand",
        "Nicaragua",
        "Niger",
        "Nigeria",
        "Niue",
        "Norfolk Island",
        "Northern Mariana Islands",
        "Norway",
        "Oman",
        "Pakistan",
        "Palau",
        "Palestine, State of",
        "Panama",
        "Papua New Guinea",
        "Paraguay",
        "Peru",
        "Philippines",
        "Pitcairn",
        "Poland",
        "Portugal",
        "Puerto Rico",
        "Qatar",
        "Romania",
        "Russian Federation",
        "Rwanda",
        "Saint Helena, Ascension and Tristan da Cunha",
        "Saint Kitts and Nevis",
        "Saint Lucia",
        "Saint Martin (French part)",
        "Saint Pierre and Miquelon",
        "Saint Vincent and the Grenadines",
        "Samoa",
        "San Marino",
        "Saudi Arabia",
        "Senegal",
        "Serbia",
        "Seychelles",
        "Sierra Leone",
        "Singapore",
        "Sint Maarten (Dutch part)",
        "Slovakia",
        "Slovenia",
        "Solomon Islands",
        "Somalia",
        "South Africa",
        "South Georgia and the South Sandwich Islands",
        "South Sudan",
        "Spain",
        "Sri Lanka",
        "Sudan",
        "Suriname",
        "Svalbard and Jan Mayen",
        "Swaziland",
        "Sweden",
        "Switzerland",
        "Syrian Arab Republic",
        "Taiwan, Province of China",
        "Tajikistan",
        "Tanzania, United Republic of",
        "Thailand",
        "Timor-Leste",
        "Togo",
        "Tokelau",
        "Tonga",
        "Trinidad and Tobago",
        "Tunisia",
        "Turkey",
        "Turkmenistan",
        "Turks and Caicos Islands",
        "Tuvalu",
        "Uganda",
        "Ukraine",
        "United Arab Emirates",
        "United Kingdom of Great Britain and Northern Ireland",
        "United States Minor Outlying Islands",
        "United States of America",
        "Uruguay",
        "Uzbekistan",
        "Vanuatu",
        "Venezuela (Bolivarian Republic of)",
        "Vietnam",
        "Virgin Islands (British)",
        "Virgin Islands (U.S.)",
        "Wallis and Futuna",
        "Western Sahara",
        "Yemen",
        "Zambia",
        "Zimbabwe"

    ]

    for country in countries:
        cntry_mstr.objects.get_or_create(
            country_name=country
        )

    # ---------------- NATIONALITY ----------------

    nationalities = [
        "AFGHAN",
        "ALBANIAN",
        "ALGERIAN",
        "AMERICAN SAMOAN",
        "ANDORRAN",
        "ANGOLAN",
        "ANGUILLAN",
        "ANTARCTIC",
        "ANTIGUAN OR BARBUDAN",
        "ARGENTINE",
        "ARMENIAN",
        "ARUBAN",
        "AUSTRALIAN",
        "AUSTRIAN",
        "AZERI",
        "AZERBAIJANI",
        "BAHAMIAN",
        "BAHRAINIAN",
        "BANGLADESHI",
        "BARBADIAN",
        "BELARUSIAN",
        "BELGIAN",
        "BELIZEAN",
        "BENINESE",
        "BENINOIS",
        "BERMUDIAN",
        "BERMUDAN",
        "BHUTANESE",
        "BOLIVIAN",
        "BONAIRE",
        "HERZEGOVINIAN",
        "BOSNIAN",
        "MOTSWANA",
        "BOTSWANAN",
        "BOUVET ISLAND",
        "BRAZILIAN",
        "BIOT",
        "BRUNEIAN",
        "BULGARIAN",
        "BURUNDIAN",
        "CABO VERDEAN",
        "CAMBODIAN",
        "CAMEROONIAN",
        "CANADIAN",
        "CAYMANIAN",
        "CENTRAL AFRICAN",
        "CHADIAN",
        "CHILEAN",
        "CHINESE",
        "CHRISTMAS ISLAND",
        "COCOS ISLAND",
        "COLOMBIAN",
        "COMORIAN",
        "COMORAN",
        "CONGOLESE",
        "COOK ISLAND",
        "COSTA RICAN",
        "IVORIAN",
        "CROATIAN",
        "CUBAN",
        "CURAÇAOAN",
        "CYPRIOT",
        "CZECH",
        "DANISH",
        "DJIBOUTIAN",
        "DOMINICAN",
        "ECUADORIAN",
        "EGYPTIAN",
        "SALVADORAN",
        "EQUATOGUINEAN",
        "EQUATORIAL GUINEAN",
        "ERITREAN",
        "ESTONIAN",
        "ETHIOPIAN",
        "FALKLAND ISLAND",
        "FAROESE",
        "FIJIAN",
        "FINNISH",
        "FRENCH",
        "FRENCH GUIANESE",
        "FRENCH POLYNESIAN",
        "FRENCH SOUTHERN TERRITORIES",
        "GABONESE",
        "GAMBIAN",
        "GEORGIAN",
        "GERMAN",
        "GHANAIAN",
        "GIBRALTAR",
        "GREEK, HELLENIC",
        "GREENLANDIC",
        "GRENADIAN",
        "GUADELOUPE",
        "GUAMBAT",
        "GUAMANIAN",
        "GUATEMALAN",
        "CHANNEL ISLAND",
        "GUINEAN",
        "BISSAU-GUINEAN",
        "GUYANESE",
        "HAITIAN",
        "MCDONALD ISLANDS",
        "HEARD ISLAND",
        "VATICAN",
        "HONDURAN",
        "HONG KONGESE",
        "HONG KONG",
        "MAGYAR",
        "HUNGARIAN",
        "ICELANDIC",
        "INDIAN",
        "INDONESIAN",
        "PERSIAN",
        "IRANIAN",
        "IRAQI",
        "IRISH",
        "MANX",
        "ISRAELI",
        "ITALIAN",
        "JAMAICAN",
        "JAPANESE",
        "CHANNEL ISLAND",
        "JORDANIAN",
        "KAZAKH",
        "KAZAKHSTANI",
        "KENYAN",
        "I-KIRIBATI",
        "NORTH KOREAN",
        "SOUTH KOREAN",
        "KUWAITI",
        "KYRGYZ",
        "KIRGIZ",
        "KIRGHIZ",
        "KYRGYZSTANI",
        "LAOTIAN",
        "LAO",
        "LATVIAN",
        "LEBANESE",
        "BASOTHO",
        "LIBERIAN",
        "LIBYAN",
        "LIECHTENSTEIN",
        "LITHUANIAN",
        "LUXEMBOURG",
        "LUXEMBOURGISH",
        "MACANESE",
        "MACEDONIAN",
        "MALAGASY",
        "MALAWIAN",
        "MALAYSIAN",
        "MALDIVIAN",
        "MALIAN",
        "MALINESE",
        "MALTESE",
        "MARSHALLESE",
        "MARTINIQUAIS",
        "MARTINICAN",
        "MAURITANIAN",
        "MAURITIAN",
        "MAHORAN",
        "MEXICAN",
        "MICRONESIAN",
        "MOLDOVAN",
        "MONGOLIAN",
        "MONTENEGRIN",
        "MONTSERRATIAN",
        "MOROCCAN",
        "MOZAMBICAN",
        "BURMESE",
        "NAMIBIAN",
        "NAURUAN",
        "NEPALI",
        "NEPALESE",
        "DUTCH",
        "NETHERLANDIC",
        "NEW CALEDONIAN",
        "NEW ZEALAND",
        "NICARAGUAN",
        "NIGERIEN",
        "NIGERIAN",
        "NIUEAN"
    ]

    for nationality in nationalities:
        Nationality.objects.get_or_create(
            N_name=nationality
        )

    # ---------------- RELIGION ----------------

    religions = [
        "Islam",
        "Christianity",
        "Hinduism",
        "Buddhism",
        "Sikhism",
        "Judaism",
        "Jainism",
        "Zoroastrianism",
        "Atheist",
        "Agnostic",
        "Other",
    ]

    for religion in religions:
        ReligionMaster.objects.get_or_create(
            religion=religion
        )