# Generated by Django 5.2.17 on 2026-10-07 15:57

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CostCenter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=30, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("department_id", models.IntegerField(blank=True, null=True)),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="ExpenseAdvance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(blank=True, max_length=20, unique=True)),
                ("employee_id", models.IntegerField(db_index=True)),
                ("branch_id", models.IntegerField(blank=True, null=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("date", models.DateField()),
                ("purpose", models.CharField(blank=True, default="", max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("requested", "Requested"),
                            ("approved", "Approved"),
                            ("paid", "Paid"),
                            ("settled", "Settled"),
                            ("rejected", "Rejected"),
                        ],
                        default="requested",
                        max_length=10,
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Payment reference",
                        max_length=100,
                    ),
                ),
                ("approved_by_id", models.IntegerField(blank=True, null=True)),
                ("paid_on", models.DateField(blank=True, null=True)),
                ("created_by_id", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="ExpenseCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("code", models.CharField(max_length=30, unique=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("general", "General"),
                            ("mileage", "Mileage"),
                            ("per_diem", "Per diem"),
                            ("travel", "Travel"),
                            ("hotel", "Hotel"),
                            ("meals", "Meals"),
                        ],
                        default="general",
                        max_length=20,
                    ),
                ),
                (
                    "gl_account",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Expense account code in the books",
                        max_length=50,
                    ),
                ),
                (
                    "receipt_required_above",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="A receipt is needed when the amount (AED) is above this; empty = never",
                        max_digits=12,
                        null=True,
                    ),
                ),
                ("description_required", models.BooleanField(default=False)),
                ("description", models.TextField(blank=True, default="")),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "expense categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ExpensePolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "category_ids",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Employee categories (empty = all)",
                    ),
                ),
                (
                    "branch_ids",
                    models.JSONField(
                        blank=True, default=list, help_text="Branches (empty = all)"
                    ),
                ),
                (
                    "grade_ids",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Grades = designations (empty = all)",
                    ),
                ),
                (
                    "mileage_rate",
                    models.DecimalField(
                        decimal_places=3,
                        default=Decimal("0.500"),
                        help_text="Per km",
                        max_digits=8,
                    ),
                ),
                (
                    "per_diem_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Per day",
                        max_digits=10,
                    ),
                ),
                ("currency", models.CharField(default="AED", max_length=3)),
                (
                    "approval_roles",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Approval levels by role, e.g. ['reporting_manager', 'branch_hr']",
                    ),
                ),
                ("is_default", models.BooleanField(default=False)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "expense policies",
                "ordering": ["-is_default", "name"],
            },
        ),
        migrations.CreateModel(
            name="ExpenseSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payable_account",
                    models.CharField(
                        default="2150",
                        help_text="Employee payable / reimbursements due",
                        max_length=50,
                    ),
                ),
                (
                    "advance_account",
                    models.CharField(
                        default="1450",
                        help_text="Employee advances (clearing)",
                        max_length=50,
                    ),
                ),
                (
                    "default_expense_account",
                    models.CharField(
                        default="6990",
                        help_text="For categories without an account",
                        max_length=50,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "expense settings",
            },
        ),
        migrations.CreateModel(
            name="Trip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(blank=True, max_length=20, unique=True)),
                ("employee_id", models.IntegerField(db_index=True)),
                ("branch_id", models.IntegerField(blank=True, null=True)),
                ("department_id", models.IntegerField(blank=True, null=True)),
                ("purpose", models.CharField(max_length=200)),
                (
                    "from_place",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("to_place", models.CharField(blank=True, default="", max_length=100)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "estimated_cost",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "advance_requested",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("closed", "Closed"),
                        ],
                        default="draft",
                        max_length=12,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("created_by_id", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-start_date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="ExpenseReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(blank=True, max_length=20, unique=True)),
                ("employee_id", models.IntegerField(db_index=True)),
                ("branch_id", models.IntegerField(blank=True, null=True)),
                ("department_id", models.IntegerField(blank=True, null=True)),
                ("title", models.CharField(max_length=200)),
                ("from_date", models.DateField(blank=True, null=True)),
                ("to_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Awaiting approval"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("sent_back", "Sent back"),
                            ("reimbursed", "Reimbursed"),
                        ],
                        default="draft",
                        max_length=12,
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "advance_applied",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "amount_to_reimburse",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "reimburse_via",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("direct", "Direct (bank / cash)"),
                            ("payroll", "With the payroll"),
                        ],
                        default="",
                        max_length=10,
                    ),
                ),
                ("reimbursed_on", models.DateField(blank=True, null=True)),
                (
                    "reimbursement_reference",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("payroll_run_id", models.IntegerField(blank=True, null=True)),
                (
                    "round",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Approval round (a sent-back report starts a new one)",
                    ),
                ),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, default="")),
                ("created_by_id", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "policy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ExpenseManagement.expensepolicy",
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reports",
                        to="ExpenseManagement.trip",
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
                "permissions": (
                    ("reimburse_expensereport", "Can reimburse expense reports"),
                    ("export_expensereport", "Can export expense accounting entries"),
                ),
            },
        ),
        migrations.CreateModel(
            name="AdvanceApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "advance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="ExpenseManagement.expenseadvance",
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="advance_lines",
                        to="ExpenseManagement.expensereport",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExpenseApproval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("round", models.PositiveSmallIntegerField(default=1)),
                ("level", models.PositiveSmallIntegerField(default=1)),
                ("approver_user_id", models.IntegerField(db_index=True)),
                ("role", models.CharField(blank=True, default="", max_length=30)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("waiting", "Waiting (earlier level first)"),
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("sent_back", "Sent back"),
                            ("skipped", "Skipped"),
                        ],
                        default="waiting",
                        max_length=10,
                    ),
                ),
                ("note", models.TextField(blank=True, default="")),
                ("acted_by_user_id", models.IntegerField(blank=True, null=True)),
                ("acted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "report",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approvals",
                        to="ExpenseManagement.expensereport",
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approvals",
                        to="ExpenseManagement.trip",
                    ),
                ),
            ],
            options={
                "ordering": ["round", "level", "id"],
            },
        ),
        migrations.AddField(
            model_name="expenseadvance",
            name="trip",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="advances",
                to="ExpenseManagement.trip",
            ),
        ),
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("employee_id", models.IntegerField(db_index=True)),
                ("branch_id", models.IntegerField(blank=True, null=True)),
                ("date", models.DateField()),
                ("merchant", models.CharField(blank=True, default="", max_length=150)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                ("currency", models.CharField(default="AED", max_length=3)),
                (
                    "exchange_rate",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("1"), max_digits=12
                    ),
                ),
                (
                    "amount_aed",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                (
                    "receipt",
                    models.FileField(
                        blank=True, null=True, upload_to="expense_receipts/%Y/%m/"
                    ),
                ),
                (
                    "mileage_km",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "mileage_from",
                    models.CharField(blank=True, default="", max_length=150),
                ),
                (
                    "mileage_to",
                    models.CharField(blank=True, default="", max_length=150),
                ),
                (
                    "per_diem_days",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=6, null=True
                    ),
                ),
                ("project_id", models.IntegerField(blank=True, null=True)),
                ("department_id", models.IntegerField(blank=True, null=True)),
                ("billable", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("unreported", "Unreported"),
                            ("submitted", "Submitted"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("reimbursed", "Reimbursed"),
                        ],
                        default="unreported",
                        max_length=12,
                    ),
                ),
                ("policy_violations", models.JSONField(blank=True, default=list)),
                ("created_by_id", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cost_center",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ExpenseManagement.costcenter",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="expenses",
                        to="ExpenseManagement.expensecategory",
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="expenses",
                        to="ExpenseManagement.expensereport",
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="expenses",
                        to="ExpenseManagement.trip",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="ExpensePolicyLimit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "per_expense_limit",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "per_day_limit",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "per_report_limit",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "block_or_warn",
                    models.CharField(
                        choices=[("warn", "Warn"), ("block", "Block")],
                        default="warn",
                        max_length=5,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="policy_limits",
                        to="ExpenseManagement.expensecategory",
                    ),
                ),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="limits",
                        to="ExpenseManagement.expensepolicy",
                    ),
                ),
            ],
            options={
                "ordering": ["policy", "category__name"],
                "unique_together": {("policy", "category")},
            },
        ),
    ]
