# Generated by Django 5.2.17 on 2026-10-06 08:17

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Core", "0001_initial"),
        ("EmpManagement", "0001_initial"),
        ("OrganisationManager", "0001_initial"),
        ("calendars", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AdvanceApprovalWorkflow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "approval_type",
                    models.CharField(
                        choices=[
                            ("no_approval", "No Approval"),
                            ("reporting_manager", "Reporting Manager"),
                            ("multi_approval", "Multi Approval"),
                        ],
                        default="no_approval",
                        max_length=30,
                    ),
                ),
                (
                    "branch",
                    models.ManyToManyField(
                        blank=True, to="OrganisationManager.brnch_mstr"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AdvanceCommonWorkflow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("level", models.PositiveIntegerField()),
                ("role", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "escalate_after_days",
                    models.PositiveIntegerField(
                        default=0, help_text="Escalate after X days if pending"
                    ),
                ),
                (
                    "escalate_after_hours",
                    models.PositiveIntegerField(
                        default=0, help_text="Escalate after X hours if pending"
                    ),
                ),
                (
                    "escalate_after_minutes",
                    models.PositiveIntegerField(
                        default=0, help_text="Escalate after X minutes if pending"
                    ),
                ),
                (
                    "approver",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "escalate_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="adv_salary_escalated_levels",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="advance_levels",
                        to="PayrollManagement.advanceapprovalworkflow",
                    ),
                ),
            ],
            options={
                "ordering": ["level"],
                "permissions": (
                    ("add_advsalary_escalation", "Can add Escalation"),
                    ("view_advsalary_escalation", "Can view Escalation"),
                    ("change_advsalary_escalation", "Can change Escalation"),
                    ("export_advsalary_escalation", "Can export Escalation"),
                    ("delete_advsalary_escalation", "Can delete Escalation"),
                ),
            },
        ),
        migrations.CreateModel(
            name="AdvanceSalaryEmailTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "template_type",
                    models.CharField(
                        choices=[
                            ("request_created", "Request Created"),
                            ("request_approved", "Request Approved"),
                            ("request_rejected", "Request Rejected"),
                        ],
                        max_length=50,
                    ),
                ),
                ("subject", models.CharField(max_length=255)),
                ("body", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "Category",
                    models.ManyToManyField(
                        blank=True, to="OrganisationManager.ctgry_master"
                    ),
                ),
                (
                    "Department",
                    models.ManyToManyField(
                        blank=True, to="OrganisationManager.dept_master"
                    ),
                ),
                (
                    "Designation",
                    models.ManyToManyField(
                        blank=True, to="OrganisationManager.desgntn_master"
                    ),
                ),
                (
                    "branch",
                    models.ManyToManyField(
                        blank=True, to="OrganisationManager.brnch_mstr"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AdvanceSalaryNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_read", models.BooleanField(default=False)),
                (
                    "deligate_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="advsalary_deligated_notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "recipient_employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="advance_salary_notification",
                        to="EmpManagement.emp_master",
                    ),
                ),
                (
                    "recipient_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AdvanceSalaryRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_number",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                (
                    "requested_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("reason", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Approved", "Approved"),
                            ("Rejected", "Rejected"),
                            ("Cancelled", "Cancelled"),
                            ("Deducted", "Deducted"),
                            ("Paused", "Paused"),
                        ],
                        default="Pending",
                        max_length=20,
                    ),
                ),
                ("remarks", models.TextField(blank=True, null=True)),
                ("pause_start_date", models.DateField(blank=True, null=True)),
                ("resume_date", models.DateField(blank=True, null=True)),
                ("pause_reason", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "branch",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="OrganisationManager.brnch_mstr",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="advance_salary_requests",
                        to="EmpManagement.emp_master",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AdvanceSalaryApproval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role", models.CharField(blank=True, max_length=100, null=True)),
                ("level", models.PositiveIntegerField()),
                ("note", models.TextField(blank=True, null=True)),
                ("is_deligate", models.BooleanField(default=False)),
                ("deligate_response", models.TextField(blank=True, null=True)),
                ("escalated", models.BooleanField(default=False)),
                ("escalated_at", models.DateTimeField(blank=True, null=True)),
                ("is_escalation", models.BooleanField(default=False)),
                ("rejection_reason", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Approved", "Approved"),
                            ("Rejected", "Rejected"),
                            ("Escalated", "Escalated"),
                        ],
                        default="Pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateField(auto_now=True)),
                (
                    "approver",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deligate_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="advsalary_deligations_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="EmpManagement.emp_master",
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approvals",
                        to="PayrollManagement.advancesalaryrequest",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AirticketApprovalWorkflow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "approval_type",
                    models.CharField(
                        choices=[
                            ("no_approval", "No Approval"),
                            ("reporting_manager", "Reporting Manager"),
                            ("multi_approval", "Multi Approval"),
                        ],
                        default="no_approval",
                        max_length=30,
                    ),
                ),
                (
                    "branch",
                    models.ManyToManyField(
                        blank=True, to="OrganisationManager.brnch_mstr"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AirticketEmailTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "template_type",
                    models.CharField(
                        choices=[
                            ("request_created", "Request Created"),
                            ("request_approved", "Request Approved"),
                            ("request_rejected", "Request Rejected"),
                        ],
                        max_length=50,
                    ),
                ),
                ("subject", models.CharField(max_length=255)),
                ("body", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "Category",
                    models.ManyToManyField(
                        blank=True, to="OrganisationManager.ctgry_master"
                    ),
                ),
                (
                    "Department",
                    models.ManyToManyField(
                        blank=True, to="OrganisationManager.dept_master"
                    ),
                ),
                (
                    "Designation",
                    models.ManyToManyField(
                        blank=True, to="OrganisationManager.desgntn_master"
                    ),
                ),
                (
                    "branch",
                    models.ManyToManyField(
                        blank=True, to="OrganisationManager.brnch_mstr"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AirticketNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_read", models.BooleanField(default=False)),
                ("is_deligate", models.BooleanField(default=False)),
                (
                    "deligate_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="airticket_deligated_notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "recipient_employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="EmpManagement.emp_master",
                    ),
                ),
                (
                    "recipient_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AirTicketPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("allowed_in_probation", models.BooleanField(default=False)),
                ("frequency_years", models.PositiveIntegerField(default=1)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "allowance_type",
                    models.CharField(
                        choices=[
                            ("CASH", "Cash"),
                            ("TICKET", "Ticket"),
                            ("BOTH", "Both"),
                        ],
                        default="TICKET",
                        max_length=10,
                    ),
                ),
                (
                    "travel_class",
                    models.CharField(
                        choices=[
                            ("ECONOMY", "Economy"),
                            ("BUSINESS", "Business"),
                            ("FIRST", "First Class"),
                        ],
                        default="ECONOMY",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "branch",
                    models.ManyToManyField(
                        blank=True, to="OrganisationManager.brnch_mstr"
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="air_ticket_country",
                        to="Core.cntry_mstr",
                    ),
                ),
                (
                    "eligible_categories",
                    models.ManyToManyField(
                        blank=True, to="OrganisationManager.ctgry_master"
                    ),
                ),
                (
                    "eligible_departments",
                    models.ManyToManyField(
                        blank=True, to="OrganisationManager.dept_master"
                    ),
                ),
                (
                    "eligible_designations",
                    models.ManyToManyField(
                        blank=True, to="OrganisationManager.desgntn_master"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AirTicketAllocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "remaining_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("allocated_date", models.DateField(auto_now_add=True)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "allocated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="allocated_tickets",
                        to="EmpManagement.emp_master",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="air_ticket_allocations",
                        to="EmpManagement.emp_master",
                    ),
                ),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="PayrollManagement.airticketpolicy",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AirTicketRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_number",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                (
                    "request_type",
                    models.CharField(
                        choices=[("TICKET", "Ticket"), ("ENCASHMENT", "Encashment")],
                        default="TICKET",
                        max_length=20,
                    ),
                ),
                ("request_date", models.DateField()),
                ("departure_date", models.DateField(blank=True, null=True)),
                ("return_date", models.DateField(blank=True, null=True)),
                ("origin", models.CharField(blank=True, max_length=100)),
                ("destination", models.CharField(blank=True, max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("PROCESSED", "Processed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("approved_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "allocation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="PayrollManagement.airticketallocation",
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_tickets",
                        to="EmpManagement.emp_master",
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="OrganisationManager.brnch_mstr",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="airticket_requests",
                        to="EmpManagement.emp_master",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AirticketApproval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role", models.CharField(blank=True, max_length=100, null=True)),
                ("level", models.PositiveIntegerField()),
                ("note", models.TextField(blank=True, null=True)),
                ("is_deligate", models.BooleanField(default=False)),
                ("deligate_response", models.TextField(blank=True, null=True)),
                ("escalated", models.BooleanField(default=False)),
                ("escalated_at", models.DateTimeField(blank=True, null=True)),
                ("is_escalation", models.BooleanField(default=False)),
                ("rejection_reason", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Approved", "Approved"),
                            ("Rejected", "Rejected"),
                            ("Escalated", "Escalated"),
                        ],
                        default="Pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approver",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deligate_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="airticket_deligations_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="EmpManagement.emp_master",
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approvals",
                        to="PayrollManagement.airticketrequest",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AirTicketRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rule_type",
                    models.CharField(
                        choices=[
                            ("ONE_WAY", "One Way Ticket"),
                            ("TWO_WAY", "Two Way Ticket"),
                            ("ENCASHMENT", "Encashment"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "required_service_years",
                    models.PositiveIntegerField(
                        help_text="Minimum years of service for this rule"
                    ),
                ),
                (
                    "apply_in_next_payroll",
                    models.BooleanField(
                        default=False,
                        help_text="For encashment: Apply in next payroll?",
                    ),
                ),
                ("remarks", models.TextField(blank=True)),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rules",
                        to="PayrollManagement.airticketpolicy",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LoanApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_number",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                (
                    "amount_requested",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("repayment_period", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Approved", "Approved"),
                            ("Rejected", "Rejected"),
                            ("Disbursed", "Disbursed"),
                            ("Rejected", "Rejected"),
                            ("Paused", "Paused"),
                            ("In Progress", "In Progress"),
                            ("Closed", "Closed"),
                        ],
                        default="Pending",
                        max_length=20,
                    ),
                ),
                (
                    "emi_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("disbursement_date", models.DateField(blank=True, null=True)),
                (
                    "remaining_balance",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("applied_on", models.DateTimeField(auto_now_add=True)),
                ("approved_on", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True, null=True)),
                ("pause_start_date", models.DateField(blank=True, null=True)),
                ("resume_date", models.DateField(blank=True, null=True)),
                ("pause_reason", models.TextField(blank=True, null=True)),
                (
                    "branch",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="OrganisationManager.brnch_mstr",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loan",
                        to="EmpManagement.emp_master",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LoanApproval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role", models.CharField(blank=True, max_length=50, null=True)),
                ("level", models.IntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Approved", "Approved"),
                            ("Rejected", "Rejected"),
                            ("Escalated", "Escalated"),
                        ],
                        default="Pending",
                        max_length=20,
                    ),
                ),
                ("note", models.TextField(blank=True, null=True)),
                ("is_deligate", models.BooleanField(default=False)),
                ("deligate_response", models.TextField(blank=True, null=True)),
                ("escalated", models.BooleanField(default=False)),
                ("escalated_at", models.DateTimeField(blank=True, null=True)),
                ("is_escalation", models.BooleanField(default=False)),
                ("rejection_reason", models.TextField(blank=True, null=True)),
                ("created_at", models.DateField(auto_now_add=True)),
                ("updated_at", models.DateField(auto_now=True)),
                ("employee_id", models.IntegerField(blank=True, null=True)),
                (
                    "approver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deligate_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="loan_deligations_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "loan_request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approvals",
                        to="PayrollManagement.loanapplication",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LoanEmailTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "template_type",
                    models.CharField(
                        choices=[
                            ("request_created", "Request Created"),
                            ("request_approved", "Request Approved"),
                            ("request_rejected", "Request Rejected"),
                        ],
                        max_length=50,
                    ),
                ),
                ("subject", models.CharField(max_length=255)),
                ("body", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "Category",
                    models.ManyToManyField(
                        blank=True, to="OrganisationManager.ctgry_master"
                    ),
                ),
                (
                    "Department",
                    models.ManyToManyField(
                        blank=True, to="OrganisationManager.dept_master"
                    ),
                ),
                (
                    "Designation",
                    models.ManyToManyField(
                        blank=True, to="OrganisationManager.desgntn_master"
                    ),
                ),
                (
                    "branch",
                    models.ManyToManyField(
                        blank=True, to="OrganisationManager.brnch_mstr"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LoanNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_read", models.BooleanField(default=False)),
                (
                    "deligate_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loan_deligated_notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "recipient_employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loan_notification",
                        to="EmpManagement.emp_master",
                    ),
                ),
                (
                    "recipient_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LoanType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("loan_type", models.CharField(max_length=255)),
                ("max_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("repayment_period", models.PositiveIntegerField()),
                (
                    "min_approvals_required",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Minimum number of approvals required to approve the request",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("use_common_workflow", models.BooleanField(default=False)),
                (
                    "branch",
                    models.ManyToManyField(
                        blank=True, to="OrganisationManager.brnch_mstr"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LoanApprovalWorkflow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "approval_type",
                    models.CharField(
                        choices=[
                            ("no_approval", "No Approval"),
                            ("reporting_manager", "Reporting Manager"),
                            ("multi_approval", "Multi Approval"),
                        ],
                        default="no_approval",
                        max_length=30,
                    ),
                ),
                (
                    "branch",
                    models.ManyToManyField(
                        blank=True, to="OrganisationManager.brnch_mstr"
                    ),
                ),
                (
                    "loan_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loan_approval_workflows",
                        to="PayrollManagement.loantype",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="loanapplication",
            name="loan_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="PayrollManagement.loantype",
            ),
        ),
        migrations.CreateModel(
            name="PayrollRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Optional payroll run name",
                        max_length=100,
                    ),
                ),
                (
                    "arabic_name",
                    models.CharField(
                        blank=True, help_text="arabic payroll run name", max_length=100
                    ),
                ),
                (
                    "month",
                    models.IntegerField(
                        choices=[
                            (1, "January"),
                            (2, "February"),
                            (3, "March"),
                            (4, "April"),
                            (5, "May"),
                            (6, "June"),
                            (7, "July"),
                            (8, "August"),
                            (9, "September"),
                            (10, "October"),
                            (11, "November"),
                            (12, "December"),
                        ],
                        help_text="Month of the payroll period",
                    ),
                ),
                ("year", models.IntegerField(help_text="Year of the payroll period")),
                ("attendance_start_date", models.DateField(blank=True, null=True)),
                ("attendance_end_date", models.DateField(blank=True, null=True)),
                (
                    "payment_date",
                    models.DateField(
                        blank=True, help_text="When employees will be paid", null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processed", "Processed"),
                            ("approved", "Approved"),
                            ("paid", "Paid"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ManyToManyField(
                        blank=True, null=True, to="OrganisationManager.ctgry_master"
                    ),
                ),
                (
                    "department",
                    models.ManyToManyField(
                        blank=True, null=True, to="OrganisationManager.dept_master"
                    ),
                ),
                (
                    "designation",
                    models.ManyToManyField(
                        blank=True, null=True, to="OrganisationManager.desgntn_master"
                    ),
                ),
                (
                    "employees",
                    models.ManyToManyField(
                        blank=True, null=True, to="EmpManagement.emp_master"
                    ),
                ),
            ],
            options={
                "permissions": (
                    ("add_wps", "Can add wps"),
                    ("view_wps", "Can view wps"),
                    ("change_wps", "Can change wps"),
                    ("export_wps", "Can export wps"),
                    ("delete_wps", "Can delete wps"),
                ),
            },
        ),
        migrations.CreateModel(
            name="LeaveEncashment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "leave_balance",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "encashment_days",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "basic_salary",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "total_salary",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "fixed_days",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("30.00"), max_digits=10
                    ),
                ),
                (
                    "calendar_days",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("30.00"), max_digits=10
                    ),
                ),
                ("formula_used", models.TextField(blank=True, null=True)),
                (
                    "encashment_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending", "Pending Approval"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("processed", "Processed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("remarks", models.TextField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_leave_encashments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="leave_encashments",
                        to="EmpManagement.emp_master",
                    ),
                ),
                (
                    "leave_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="leave_encashments",
                        to="calendars.leave_type",
                    ),
                ),
                (
                    "payroll_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="leave_encashments",
                        to="PayrollManagement.payrollrun",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PayrollRunBranch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("document_number", models.CharField(max_length=50, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="OrganisationManager.brnch_mstr",
                    ),
                ),
                (
                    "payroll_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="branch_documents",
                        to="PayrollManagement.payrollrun",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="payrollrun",
            name="branch",
            field=models.ManyToManyField(
                blank=True,
                related_name="payroll_runs",
                through="PayrollManagement.PayrollRunBranch",
                to="OrganisationManager.brnch_mstr",
            ),
        ),
        migrations.CreateModel(
            name="Payslip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gross_salary",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "net_salary",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "total_deductions",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "total_additions",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processed", "Processed"),
                            ("paid", "Paid"),
                            ("rejected", "Rejected"),
                            ("Approved", "Approved"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "total_working_days",
                    models.PositiveIntegerField(
                        default=0, help_text="Total working days in the payroll period"
                    ),
                ),
                (
                    "days_worked",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of days the employee worked"
                    ),
                ),
                (
                    "pro_rata_adjustment",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Pro-rata adjustment",
                        max_digits=10,
                    ),
                ),
                (
                    "arrears",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Arrears amount",
                        max_digits=10,
                    ),
                ),
                (
                    "send_email",
                    models.BooleanField(
                        default=False, help_text="Send this payslip via email if True"
                    ),
                ),
                (
                    "payslip_pdf",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="payslips/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["pdf"]
                            )
                        ],
                    ),
                ),
                (
                    "confirm_status",
                    models.BooleanField(
                        default=False, help_text="confirm this payslip if True"
                    ),
                ),
                (
                    "trial_status",
                    models.BooleanField(
                        default=False, help_text="confirm this payslip if True"
                    ),
                ),
                ("rejection_reason", models.TextField(blank=True, null=True)),
                (
                    "currency",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Core.crncy_mstr",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payslips",
                        to="EmpManagement.emp_master",
                    ),
                ),
                (
                    "payroll_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payslips",
                        to="PayrollManagement.payrollrun",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LoanRepayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("repayment_date", models.DateField(auto_now_add=True, null=True)),
                ("amount_paid", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "remaining_balance",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "loan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="PayrollManagement.loanapplication",
                    ),
                ),
                (
                    "payslip",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="PayrollManagement.payslip",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PayslipApproval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role", models.CharField(blank=True, max_length=100, null=True)),
                ("level", models.PositiveIntegerField()),
                ("note", models.TextField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Approved", "Approved"),
                            ("Rejected", "Rejected"),
                        ],
                        default="Pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "approver",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="EmpManagement.emp_master",
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approvals",
                        to="PayrollManagement.payslip",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PayslipApprovalWorkflow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "approval_type",
                    models.CharField(
                        choices=[
                            ("no_approval", "No Approval"),
                            ("reporting_manager", "Reporting Manager"),
                            ("multi_approval", "Multi Approval"),
                        ],
                        default="no_approval",
                        max_length=30,
                    ),
                ),
                (
                    "branch",
                    models.ManyToManyField(
                        blank=True, to="OrganisationManager.brnch_mstr"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PayslipCommonWorkflow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("level", models.PositiveIntegerField()),
                ("role", models.CharField(max_length=100)),
                (
                    "approver",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payslip_levels",
                        to="PayrollManagement.payslipapprovalworkflow",
                    ),
                ),
            ],
            options={
                "ordering": ["level"],
            },
        ),
        migrations.CreateModel(
            name="PayslipLeave",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("days", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "leave_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="calendars.leave_type",
                    ),
                ),
                (
                    "payslip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_details",
                        to="PayrollManagement.payslip",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PayStructure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "working_days",
                    models.JSONField(
                        default=list,
                        help_text="Example: ['MON','TUE','WED','THU','FRI']",
                    ),
                ),
                (
                    "salary_calculation_type",
                    models.CharField(
                        choices=[
                            ("CALENDAR_DAYS", "Calendar Days"),
                            ("ORGANIZATION_DAYS", "Organization Days"),
                            ("FIXED_DAYS", "Fixed Days"),
                        ],
                        default="CALENDAR_DAYS",
                        max_length=20,
                    ),
                ),
                (
                    "fixed_working_days",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "attendance_cycle_type",
                    models.CharField(
                        choices=[
                            ("MONTH", "Calendar Month"),
                            ("CUSTOM", "Custom Cycle"),
                        ],
                        default="MONTH",
                        max_length=10,
                    ),
                ),
                (
                    "cycle_start_day",
                    models.PositiveSmallIntegerField(
                        blank=True, help_text="Example: 26", null=True
                    ),
                ),
                (
                    "cycle_end_day",
                    models.PositiveSmallIntegerField(
                        blank=True, help_text="Example: 25", null=True
                    ),
                ),
                ("payday", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "overtime_source",
                    models.CharField(
                        choices=[
                            ("ATTENDANCE", "Attendance-Based"),
                            ("MANUAL", "Manual Entry"),
                            ("COMBINED", "Combined"),
                        ],
                        default="ATTENDANCE",
                        max_length=20,
                    ),
                ),
                ("payroll_start_month", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "branch",
                    models.ManyToManyField(
                        blank=True,
                        null=True,
                        related_name="payroll_structures",
                        to="OrganisationManager.brnch_mstr",
                    ),
                ),
                (
                    "category",
                    models.ManyToManyField(
                        blank=True,
                        null=True,
                        related_name="payroll_ctgrystructures",
                        to="OrganisationManager.ctgry_master",
                    ),
                ),
                (
                    "department",
                    models.ManyToManyField(
                        blank=True,
                        null=True,
                        related_name="payroll_deptstructures",
                        to="OrganisationManager.dept_master",
                    ),
                ),
                (
                    "designation",
                    models.ManyToManyField(
                        blank=True,
                        null=True,
                        related_name="payroll_desgntnstructures",
                        to="OrganisationManager.desgntn_master",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SalaryComponent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "component_type",
                    models.CharField(
                        choices=[
                            ("deduction", "Deduction"),
                            ("addition", "Addition"),
                            ("others", "Others"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "payroll_category",
                    models.CharField(
                        choices=[
                            ("basic", "Basic Salary"),
                            ("hra", "HRA"),
                            ("education_allowance", "Education Allowance"),
                            ("transport_allowance", "Transport Allowance"),
                            ("food_allowance", "Food Allowance"),
                            ("housing_allowance", "Housing Allowance"),
                            ("telephone_allowance", "Telephone Allowance"),
                            ("medical_allowance", "Medical Allowance"),
                            ("travel_allowance", "Travel Allowance"),
                            ("other_allowance", "Other Allowance"),
                            ("bonus", "Bonus"),
                            ("commission", "Commission"),
                            ("overtime", "Overtime"),
                            ("loan", "Loan Deduction"),
                            ("advance_salary", "Advance Salary"),
                            ("air_ticket", "Air Ticket"),
                            ("gratuity", "Gratuity"),
                            ("leave_encashment", "Leave Encashment"),
                            ("pf", "Provident Fund"),
                            ("esi", "ESI"),
                            ("tax", "Tax"),
                        ],
                        default="basic",
                        max_length=50,
                    ),
                ),
                ("code", models.CharField(max_length=20, null=True)),
                ("deduct_leave", models.BooleanField(default=False)),
                (
                    "component_value_type",
                    models.CharField(
                        choices=[("fixed", "Fixed"), ("variable", "Variable")],
                        default="fixed",
                        max_length=20,
                    ),
                ),
                (
                    "formula",
                    models.CharField(
                        blank=True,
                        help_text="Formula to calculate this component (e.g., 'basic_salary * 0.4')",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "show_in_payslip",
                    models.BooleanField(
                        default=True,
                        help_text="Should this component be shown on the payslip?",
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="salary_components",
                        to="OrganisationManager.brnch_mstr",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PayslipComponent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "payslip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="components",
                        to="PayrollManagement.payslip",
                    ),
                ),
                (
                    "component",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="PayrollManagement.salarycomponent",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EmployeeSalaryStructure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0.0,
                        help_text="Amount for this component",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Is this component active for the employee?",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                (
                    "valid_from",
                    models.DateField(
                        blank=True,
                        help_text="Month from which this amount becomes active",
                        null=True,
                    ),
                ),
                (
                    "valid_until",
                    models.DateField(
                        blank=True,
                        help_text="Last month for which this amount is active",
                        null=True,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="salary_structures",
                        to="EmpManagement.emp_master",
                    ),
                ),
                (
                    "component",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employee_components",
                        to="PayrollManagement.salarycomponent",
                    ),
                ),
            ],
            options={
                "permissions": (
                    ("import_salarycomponent", "Can import Salary component"),
                ),
            },
        ),
        migrations.CreateModel(
            name="SalaryRevisionHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "old_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "new_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "effective_period",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("revised_on", models.DateTimeField(auto_now_add=True)),
                ("remarks", models.CharField(blank=True, max_length=255, null=True)),
                ("revisions", models.JSONField(blank=True, default=list)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                (
                    "component",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revision_history",
                        to="PayrollManagement.salarycomponent",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="salary_revisions_history",
                        to="EmpManagement.emp_master",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SalaryStructure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the structure (e.g., Manager, Worker)",
                        max_length=100,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                (
                    "branch",
                    models.ManyToManyField(
                        blank=True,
                        null=True,
                        related_name="salary_structures",
                        to="OrganisationManager.brnch_mstr",
                    ),
                ),
                (
                    "components",
                    models.ManyToManyField(
                        help_text="Salary components included in this structure",
                        related_name="salary_structures",
                        to="PayrollManagement.salarycomponent",
                    ),
                ),
                (
                    "employees",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Employees assigned to this structure",
                        related_name="assigned_salary_structures",
                        to="EmpManagement.emp_master",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AirticketWorkflow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("level", models.PositiveIntegerField()),
                ("role", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "escalate_after_days",
                    models.PositiveIntegerField(
                        default=0, help_text="Escalate after X days if pending"
                    ),
                ),
                (
                    "escalate_after_hours",
                    models.PositiveIntegerField(
                        default=0, help_text="Escalate after X hours if pending"
                    ),
                ),
                (
                    "escalate_after_minutes",
                    models.PositiveIntegerField(
                        default=0, help_text="Escalate after X minutes if pending"
                    ),
                ),
                (
                    "approver",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "escalate_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="airticket_escalated_levels",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="airticket_levels",
                        to="PayrollManagement.airticketapprovalworkflow",
                    ),
                ),
            ],
            options={
                "ordering": ["level"],
                "permissions": (
                    ("add_airticket_escalation", "Can add Escalation"),
                    ("view_airticket_escalation", "Can view Escalation"),
                    ("change_airticket_escalation", "Can change Escalation"),
                    ("export_airticket_escalation", "Can export Escalation"),
                    ("delete_airticket_escalation", "Can delete Escalation"),
                ),
                "unique_together": {("workflow", "level")},
            },
        ),
        migrations.CreateModel(
            name="LoanApprovalLevels",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("level", models.IntegerField()),
                ("role", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "escalate_after_days",
                    models.PositiveIntegerField(
                        default=0, help_text="Escalate after X days if pending"
                    ),
                ),
                (
                    "escalate_after_hours",
                    models.PositiveIntegerField(
                        default=0, help_text="Escalate after X hours if pending"
                    ),
                ),
                (
                    "escalate_after_minutes",
                    models.PositiveIntegerField(
                        default=0, help_text="Escalate after X minutes if pending"
                    ),
                ),
                (
                    "approver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "escalate_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="loan_escalated_levels",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loan_levels",
                        to="PayrollManagement.loanapprovalworkflow",
                    ),
                ),
            ],
            options={
                "permissions": (
                    ("add_loan_escalation", "Can add Escalation"),
                    ("view_loan_escalation", "Can view Escalation"),
                    ("change_loan_escalation", "Can change Escalation"),
                    ("export_loan_escalation", "Can export Escalation"),
                    ("delete_loan_escalation", "Can delete Escalation"),
                ),
                "unique_together": {("workflow", "level")},
            },
        ),
        migrations.CreateModel(
            name="LoanCommonWorkflow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("level", models.IntegerField()),
                ("role", models.CharField(blank=True, max_length=50, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "approver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("level",), name="Loan_common_workflow_levels"
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="payrollrunbranch",
            constraint=models.UniqueConstraint(
                fields=("payroll_run", "branch"), name="unique_branch_per_payroll_run"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="payslipleave",
            unique_together={("payslip", "leave_type")},
        ),
        migrations.AddConstraint(
            model_name="salarycomponent",
            constraint=models.UniqueConstraint(
                fields=("name", "branch"),
                name="unique_salary_component_name_per_branch",
            ),
        ),
        migrations.AddConstraint(
            model_name="salarycomponent",
            constraint=models.UniqueConstraint(
                fields=("code", "branch"),
                name="unique_salary_component_code_per_branch",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="employeesalarystructure",
            unique_together={("employee", "component")},
        ),
        migrations.AlterUniqueTogether(
            name="salaryrevisionhistory",
            unique_together={("employee", "component")},
        ),
    ]
