# Generated by Django 5.2.17 on 2026-10-06 09:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Core", "0001_initial"),
        ("EmpManagement", "0002_initial"),
        ("OrganisationManager", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("applied", "Applied"),
                            ("screening", "Screening"),
                            ("interview", "Interview"),
                            ("offer", "Offer"),
                            ("hired", "Hired"),
                            ("rejected", "Rejected"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        default="applied",
                        max_length=20,
                    ),
                ),
                (
                    "screening_score",
                    models.PositiveSmallIntegerField(
                        blank=True, help_text="0-100", null=True
                    ),
                ),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        blank=True, help_text="1-5 stars", null=True
                    ),
                ),
                (
                    "rejection_reason",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("applied_on", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "screened_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="screened_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-applied_on"],
            },
        ),
        migrations.CreateModel(
            name="ApplicationStageHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("from_stage", models.CharField(blank=True, max_length=20, null=True)),
                ("to_stage", models.CharField(max_length=20)),
                ("note", models.CharField(blank=True, max_length=255, null=True)),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="RecruitmentManagement.application",
                    ),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-changed_at"],
            },
        ),
        migrations.CreateModel(
            name="Candidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=60)),
                ("last_name", models.CharField(blank=True, max_length=60, null=True)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=30, null=True)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                        max_length=1,
                        null=True,
                    ),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "current_location",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "current_employer",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "current_designation",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "experience_years",
                    models.DecimalField(decimal_places=1, default=0, max_digits=4),
                ),
                ("notice_period_days", models.PositiveIntegerField(default=30)),
                (
                    "current_salary",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "expected_salary",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "visa_status",
                    models.CharField(
                        choices=[
                            ("uae_national", "UAE National"),
                            ("gcc_national", "GCC National"),
                            ("own_visa", "Own / family visa"),
                            ("employment_visa", "Employment visa (needs transfer)"),
                            ("visit_visa", "Visit visa"),
                            ("outside_uae", "Outside UAE - needs sponsorship"),
                            ("golden_visa", "Golden visa"),
                        ],
                        default="outside_uae",
                        max_length=20,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("careers", "Careers page"),
                            ("linkedin", "LinkedIn"),
                            ("bayt", "Bayt"),
                            ("naukrigulf", "Naukrigulf"),
                            ("indeed", "Indeed"),
                            ("nafis", "Nafis portal"),
                            ("referral", "Employee referral"),
                            ("agency", "Recruitment agency"),
                            ("walk_in", "Walk-in"),
                            ("other", "Other"),
                        ],
                        default="careers",
                        max_length=20,
                    ),
                ),
                ("skills", models.TextField(blank=True, null=True)),
                ("languages", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "cv",
                    models.FileField(
                        blank=True, null=True, upload_to="recruitment/cv/"
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "consent_to_retain",
                    models.BooleanField(
                        default=False,
                        help_text="Candidate agreed that we keep the CV for future roles",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "nationality",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="candidates",
                        to="Core.nationality",
                    ),
                ),
                (
                    "referred_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="referred_candidates",
                        to="EmpManagement.emp_master",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="application",
            name="candidate",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="applications",
                to="RecruitmentManagement.candidate",
            ),
        ),
        migrations.CreateModel(
            name="CandidateDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g. Passport copy, Emirates ID copy, Degree certificate",
                        max_length=120,
                    ),
                ),
                ("file", models.FileField(upload_to="recruitment/documents/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="RecruitmentManagement.candidate",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Interview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "round_name",
                    models.CharField(default="Round 1 - Technical", max_length=80),
                ),
                ("scheduled_at", models.DateTimeField()),
                ("duration_minutes", models.PositiveIntegerField(default=60)),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("office", "In office"),
                            ("online", "Online (Teams / Zoom)"),
                            ("phone", "Phone"),
                        ],
                        default="office",
                        max_length=10,
                    ),
                ),
                (
                    "location_or_link",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("no_show", "No-show"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                (
                    "overall_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                (
                    "recommendation",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("proceed", "Proceed"),
                            ("hold", "Hold"),
                            ("reject", "Reject"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("comments", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interviews",
                        to="RecruitmentManagement.application",
                    ),
                ),
                (
                    "panel",
                    models.ManyToManyField(
                        blank=True,
                        related_name="interview_panels",
                        to="EmpManagement.emp_master",
                    ),
                ),
            ],
            options={
                "ordering": ["scheduled_at"],
            },
        ),
        migrations.CreateModel(
            name="InterviewScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("criterion", models.CharField(max_length=120)),
                (
                    "weight",
                    models.DecimalField(decimal_places=2, default=25, max_digits=5),
                ),
                ("score", models.PositiveSmallIntegerField(help_text="1-5")),
                (
                    "interview",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scores",
                        to="RecruitmentManagement.interview",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JobOpening",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_code", models.CharField(blank=True, max_length=30, unique=True)),
                ("title", models.CharField(max_length=150)),
                ("openings", models.PositiveIntegerField(default=1)),
                (
                    "employment_type",
                    models.CharField(
                        choices=[
                            ("full_time", "Full time"),
                            ("part_time", "Part time"),
                            ("contract", "Fixed-term contract"),
                            ("intern", "Internship"),
                        ],
                        default="full_time",
                        max_length=20,
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=150, null=True)),
                ("experience_min_years", models.PositiveIntegerField(default=0)),
                (
                    "min_salary",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "max_salary",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("description", models.TextField()),
                ("requirements", models.TextField(blank=True, null=True)),
                (
                    "channels",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of publishing channels",
                    ),
                ),
                ("closing_date", models.DateField(blank=True, null=True)),
                ("is_emiratisation", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("interviewing", "Interviewing"),
                            ("on_hold", "On hold"),
                            ("filled", "Filled"),
                            ("closed", "Closed"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("published_on", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="job_openings",
                        to="OrganisationManager.brnch_mstr",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="job_openings",
                        to="OrganisationManager.dept_master",
                    ),
                ),
                (
                    "designation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="job_openings",
                        to="OrganisationManager.desgntn_master",
                    ),
                ),
                (
                    "hiring_manager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="job_openings_managed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="application",
            name="job",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="applications",
                to="RecruitmentManagement.jobopening",
            ),
        ),
        migrations.CreateModel(
            name="ManpowerRequisition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_number",
                    models.CharField(blank=True, max_length=30, unique=True),
                ),
                ("position_title", models.CharField(max_length=150)),
                ("headcount", models.PositiveIntegerField(default=1)),
                (
                    "requisition_type",
                    models.CharField(
                        choices=[
                            ("new", "New position (budgeted)"),
                            ("new_unbudgeted", "New position (not budgeted)"),
                            ("replacement", "Replacement"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                (
                    "employment_type",
                    models.CharField(
                        choices=[
                            ("full_time", "Full time"),
                            ("part_time", "Part time"),
                            ("contract", "Fixed-term contract"),
                            ("intern", "Internship"),
                        ],
                        default="full_time",
                        max_length=20,
                    ),
                ),
                (
                    "min_salary",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Monthly total package (AED)",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "max_salary",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "work_location",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("target_joining_date", models.DateField(blank=True, null=True)),
                (
                    "is_emiratisation",
                    models.BooleanField(
                        default=False, help_text="Nafis / Emiratisation position"
                    ),
                ),
                ("justification", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending", "Pending approval"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("on_hold", "On hold"),
                            ("closed", "Closed"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("submitted_on", models.DateTimeField(blank=True, null=True)),
                ("approved_on", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="manpower_requisitions",
                        to="OrganisationManager.brnch_mstr",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="manpower_requisitions",
                        to="OrganisationManager.dept_master",
                    ),
                ),
                (
                    "designation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="manpower_requisitions",
                        to="OrganisationManager.desgntn_master",
                    ),
                ),
                (
                    "replacing_employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="replacement_requisitions",
                        to="EmpManagement.emp_master",
                    ),
                ),
                (
                    "reporting_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="requisitions_reporting_to",
                        to="EmpManagement.emp_master",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="manpower_requisitions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="jobopening",
            name="requisition",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="job_openings",
                to="RecruitmentManagement.manpowerrequisition",
            ),
        ),
        migrations.CreateModel(
            name="Offer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_number",
                    models.CharField(blank=True, max_length=30, unique=True),
                ),
                ("position_title", models.CharField(max_length=150)),
                (
                    "contract_type",
                    models.CharField(
                        choices=[
                            ("limited", "Limited (fixed-term)"),
                            ("unlimited", "Unlimited"),
                        ],
                        default="limited",
                        max_length=20,
                    ),
                ),
                ("contract_years", models.PositiveSmallIntegerField(default=2)),
                ("probation_months", models.PositiveSmallIntegerField(default=6)),
                ("basic_salary", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "housing_allowance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "transport_allowance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "other_allowance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("annual_leave_days", models.PositiveSmallIntegerField(default=30)),
                (
                    "air_ticket",
                    models.CharField(
                        blank=True,
                        default="Annual economy ticket to home country",
                        max_length=150,
                        null=True,
                    ),
                ),
                (
                    "medical_insurance",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("joining_date", models.DateField()),
                ("valid_until", models.DateField(blank=True, null=True)),
                ("terms", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending_approval", "Pending approval"),
                            ("approved", "Approved"),
                            ("sent", "Sent to candidate"),
                            ("accepted", "Accepted"),
                            ("declined", "Declined"),
                            ("expired", "Expired"),
                            ("withdrawn", "Withdrawn"),
                            ("joined", "Joined"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("approved_on", models.DateTimeField(blank=True, null=True)),
                ("sent_on", models.DateTimeField(blank=True, null=True)),
                ("responded_on", models.DateTimeField(blank=True, null=True)),
                (
                    "decline_reason",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "application",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offer",
                        to="RecruitmentManagement.application",
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="offers_approved",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="offers",
                        to="OrganisationManager.brnch_mstr",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="offers",
                        to="OrganisationManager.ctgry_master",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="offers_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="offers",
                        to="OrganisationManager.dept_master",
                    ),
                ),
                (
                    "designation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="offers",
                        to="OrganisationManager.desgntn_master",
                    ),
                ),
                (
                    "employee",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recruitment_offer",
                        to="EmpManagement.emp_master",
                    ),
                ),
                (
                    "reporting_manager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="offers_reporting",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OnboardingTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "team",
                    models.CharField(
                        choices=[
                            ("HR", "HR"),
                            ("IT", "IT"),
                            ("Admin", "Admin"),
                            ("Manager", "Manager"),
                            ("L&D", "L&D"),
                            ("Finance", "Finance"),
                        ],
                        default="HR",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("due_date", models.DateField(blank=True, null=True)),
                ("is_done", models.BooleanField(default=False)),
                ("done_on", models.DateTimeField(blank=True, null=True)),
                (
                    "offer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="onboarding_tasks",
                        to="RecruitmentManagement.offer",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="onboarding_tasks_owned",
                        to="EmpManagement.emp_master",
                    ),
                ),
            ],
            options={
                "ordering": ["offer", "is_done", "id"],
            },
        ),
        migrations.CreateModel(
            name="RequisitionApprovalLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("level", models.PositiveIntegerField(unique=True)),
                (
                    "role",
                    models.CharField(
                        help_text="e.g. Department Head, HR Manager, Finance, CEO",
                        max_length=80,
                    ),
                ),
                (
                    "only_above_budget",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Only required when the maximum salary is above this amount",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "approver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="requisition_approval_levels",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["level"],
            },
        ),
        migrations.CreateModel(
            name="VisaStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sequence", models.PositiveSmallIntegerField(default=1)),
                ("name", models.CharField(max_length=150)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In progress"),
                            ("done", "Done"),
                            ("not_applicable", "Not applicable"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("step_date", models.DateField(blank=True, null=True)),
                (
                    "cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "document",
                    models.FileField(
                        blank=True, null=True, upload_to="recruitment/visa/"
                    ),
                ),
                ("remarks", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "offer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visa_steps",
                        to="RecruitmentManagement.offer",
                    ),
                ),
            ],
            options={
                "ordering": ["offer", "sequence"],
            },
        ),
        migrations.AlterUniqueTogether(
            name="application",
            unique_together={("candidate", "job")},
        ),
        migrations.CreateModel(
            name="RequisitionApproval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("level", models.PositiveIntegerField()),
                ("role", models.CharField(max_length=80)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("skipped", "Skipped"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("comments", models.TextField(blank=True, null=True)),
                ("acted_on", models.DateTimeField(blank=True, null=True)),
                (
                    "acted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="requisition_approvals_acted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "approver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="requisition_approvals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requisition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approvals",
                        to="RecruitmentManagement.manpowerrequisition",
                    ),
                ),
            ],
            options={
                "ordering": ["requisition", "level"],
                "unique_together": {("requisition", "level")},
            },
        ),
    ]
