# Generated by Django 5.2.17 on 2026-10-07 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EmployeeTransfer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("employee_id", models.IntegerField(db_index=True)),
                ("effective_date", models.DateField()),
                ("from_branch_id", models.IntegerField(blank=True, null=True)),
                ("to_branch_id", models.IntegerField(blank=True, null=True)),
                ("from_department_id", models.IntegerField(blank=True, null=True)),
                ("to_department_id", models.IntegerField(blank=True, null=True)),
                ("from_designation_id", models.IntegerField(blank=True, null=True)),
                ("to_designation_id", models.IntegerField(blank=True, null=True)),
                ("from_category_id", models.IntegerField(blank=True, null=True)),
                ("to_category_id", models.IntegerField(blank=True, null=True)),
                (
                    "from_manager_id",
                    models.IntegerField(
                        blank=True, help_text="reporting manager (user id)", null=True
                    ),
                ),
                ("to_manager_id", models.IntegerField(blank=True, null=True)),
                (
                    "salary_changes",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="{component code: new monthly amount}",
                    ),
                ),
                ("options", models.JSONField(blank=True, default=dict)),
                ("reason", models.CharField(blank=True, default="", max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("done", "Done"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="scheduled",
                        max_length=12,
                    ),
                ),
                (
                    "result",
                    models.JSONField(
                        blank=True, default=dict, help_text="what was moved"
                    ),
                ),
                ("created_by_id", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("done_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-effective_date", "-id"],
                "permissions": [
                    ("run_employee_transfer", "Can carry out employee transfers")
                ],
            },
        ),
        migrations.CreateModel(
            name="RejoinSettlement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rejoining_id",
                    models.IntegerField(
                        help_text="calendars.EmployeeRejoining", unique=True
                    ),
                ),
                ("employee_id", models.IntegerField(db_index=True)),
                ("leave_request_id", models.IntegerField()),
                ("rejoin_date", models.DateField()),
                ("gap_days", models.FloatField(default=0)),
                (
                    "treatment",
                    models.CharField(
                        choices=[
                            ("unpaid", "Unpaid leave"),
                            ("leave", "From a leave balance"),
                            ("split", "Leave balance first, rest unpaid"),
                            ("absent", "Absent"),
                            ("excused", "Excused (paid, no leave)"),
                            ("early", "Early return: days back to the balance"),
                            ("on_time", "On time"),
                        ],
                        max_length=10,
                    ),
                ),
                ("leave_type_id", models.IntegerField(blank=True, null=True)),
                ("days_from_leave", models.FloatField(default=0)),
                ("unpaid_days", models.FloatField(default=0)),
                ("absent_days", models.FloatField(default=0)),
                ("excused_days", models.FloatField(default=0)),
                ("returned_days", models.FloatField(default=0)),
                ("request_ids", models.JSONField(blank=True, default=list)),
                ("note", models.CharField(blank=True, default="", max_length=255)),
                ("settled_by_id", models.IntegerField(blank=True, null=True)),
                ("settled_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
