# Generated by Django 5.2.17 on 2026-10-06 09:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("EmpManagement", "0002_initial"),
        ("OrganisationManager", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AppraisalTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, unique=True)),
                (
                    "kpi_weight",
                    models.DecimalField(decimal_places=2, default=70, max_digits=5),
                ),
                (
                    "competency_weight",
                    models.DecimalField(decimal_places=2, default=30, max_digits=5),
                ),
                ("min_goals", models.PositiveIntegerField(default=3)),
                ("max_goals", models.PositiveIntegerField(default=8)),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="AppraisalCycle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, unique=True)),
                (
                    "cycle_type",
                    models.CharField(
                        choices=[
                            ("annual", "Annual"),
                            ("half_yearly", "Half-yearly"),
                            ("probation", "Probation review"),
                        ],
                        default="annual",
                        max_length=20,
                    ),
                ),
                ("period_from", models.DateField()),
                ("period_to", models.DateField()),
                (
                    "eligible_joined_before",
                    models.DateField(
                        blank=True,
                        help_text="Only employees who joined before this date are included",
                        null=True,
                    ),
                ),
                ("goal_setting_due", models.DateField(blank=True, null=True)),
                ("checkin_due", models.DateField(blank=True, null=True)),
                ("self_appraisal_start", models.DateField(blank=True, null=True)),
                ("self_appraisal_due", models.DateField(blank=True, null=True)),
                ("manager_review_due", models.DateField(blank=True, null=True)),
                ("calibration_due", models.DateField(blank=True, null=True)),
                ("increment_effective_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("calibration", "Calibration"),
                            ("closed", "Closed"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("launched_on", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "branches",
                    models.ManyToManyField(
                        blank=True,
                        related_name="appraisal_cycles",
                        to="OrganisationManager.brnch_mstr",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="appraisal_cycles_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "departments",
                    models.ManyToManyField(
                        blank=True,
                        related_name="appraisal_cycles",
                        to="OrganisationManager.dept_master",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cycles",
                        to="PerformanceManagement.appraisaltemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["-period_from"],
            },
        ),
        migrations.CreateModel(
            name="GoalSheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Goals submitted"),
                            ("approved", "Goals approved"),
                            ("self_submitted", "Self appraisal submitted"),
                            ("reviewed", "Manager reviewed"),
                            ("calibrated", "Calibrated"),
                            ("acknowledged", "Acknowledged"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "self_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                (
                    "manager_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                (
                    "proposed_rating",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[
                            (1, "1 - Below expectations"),
                            (2, "2 - Partially meets"),
                            (3, "3 - Meets"),
                            (4, "4 - Exceeds"),
                            (5, "5 - Outstanding"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "final_rating",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[
                            (1, "1 - Below expectations"),
                            (2, "2 - Partially meets"),
                            (3, "3 - Meets"),
                            (4, "4 - Exceeds"),
                            (5, "5 - Outstanding"),
                        ],
                        null=True,
                    ),
                ),
                ("key_achievements", models.TextField(blank=True, null=True)),
                ("development_needs", models.TextField(blank=True, null=True)),
                ("manager_comments", models.TextField(blank=True, null=True)),
                ("return_reason", models.TextField(blank=True, null=True)),
                ("acknowledged_on", models.DateTimeField(blank=True, null=True)),
                ("employee_disagrees", models.BooleanField(default=False)),
                ("disagreement_note", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cycle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="goal_sheets",
                        to="PerformanceManagement.appraisalcycle",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="goal_sheets",
                        to="EmpManagement.emp_master",
                    ),
                ),
                (
                    "manager",
                    models.ForeignKey(
                        blank=True,
                        help_text="Reporting manager at launch",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="team_goal_sheets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["cycle", "employee__emp_code"],
                "unique_together": {("cycle", "employee")},
            },
        ),
        migrations.CreateModel(
            name="CheckIn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("checkin_date", models.DateField(default=django.utils.timezone.now)),
                ("manager_comments", models.TextField(blank=True, null=True)),
                ("employee_comments", models.TextField(blank=True, null=True)),
                ("goal_changes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sheet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checkins",
                        to="PerformanceManagement.goalsheet",
                    ),
                ),
            ],
            options={
                "ordering": ["-checkin_date"],
            },
        ),
        migrations.CreateModel(
            name="CalibrationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("old_rating", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "new_rating",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "1 - Below expectations"),
                            (2, "2 - Partially meets"),
                            (3, "3 - Meets"),
                            (4, "4 - Exceeds"),
                            (5, "5 - Outstanding"),
                        ]
                    ),
                ),
                ("reason", models.CharField(max_length=255)),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sheet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calibration_logs",
                        to="PerformanceManagement.goalsheet",
                    ),
                ),
            ],
            options={
                "ordering": ["-changed_at"],
            },
        ),
        migrations.CreateModel(
            name="AppraisalOutcome",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "final_rating",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "1 - Below expectations"),
                            (2, "2 - Partially meets"),
                            (3, "3 - Meets"),
                            (4, "4 - Exceeds"),
                            (5, "5 - Outstanding"),
                        ]
                    ),
                ),
                (
                    "current_basic",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "increment_percent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "new_basic",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "bonus_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("effective_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending approval"),
                            ("approved", "Approved"),
                            ("pushed", "Pushed to payroll"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("remarks", models.CharField(blank=True, max_length=255, null=True)),
                ("pushed_on", models.DateTimeField(blank=True, null=True)),
                (
                    "pushed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="appraisal_outcomes_pushed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sheet",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outcome",
                        to="PerformanceManagement.goalsheet",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="KPI",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=30, unique=True)),
                ("name", models.CharField(max_length=200)),
                (
                    "kpi_type",
                    models.CharField(
                        choices=[("kpi", "KPI"), ("competency", "Competency")],
                        default="kpi",
                        max_length=20,
                    ),
                ),
                (
                    "measure",
                    models.CharField(
                        choices=[
                            ("quantitative", "Quantitative"),
                            ("behavioural", "Behavioural"),
                        ],
                        default="quantitative",
                        max_length=20,
                    ),
                ),
                (
                    "default_weight",
                    models.DecimalField(decimal_places=2, default=10, max_digits=5),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="performance_kpis_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="performance_kpis",
                        to="OrganisationManager.dept_master",
                    ),
                ),
                (
                    "designation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="performance_kpis",
                        to="OrganisationManager.desgntn_master",
                    ),
                ),
            ],
            options={
                "ordering": ["kpi_type", "code"],
            },
        ),
        migrations.CreateModel(
            name="Goal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=250)),
                (
                    "goal_type",
                    models.CharField(
                        choices=[("kpi", "KPI"), ("competency", "Competency")],
                        default="kpi",
                        max_length=20,
                    ),
                ),
                ("weight", models.DecimalField(decimal_places=2, max_digits=5)),
                ("target", models.CharField(blank=True, max_length=250, null=True)),
                ("due_date", models.DateField(blank=True, null=True)),
                ("progress_percent", models.PositiveSmallIntegerField(default=0)),
                (
                    "progress_status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not started"),
                            ("on_track", "On track"),
                            ("ahead", "Ahead"),
                            ("at_risk", "At risk"),
                            ("off_track", "Off track"),
                            ("done", "Done"),
                        ],
                        default="not_started",
                        max_length=20,
                    ),
                ),
                (
                    "self_rating",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[
                            (1, "1 - Below expectations"),
                            (2, "2 - Partially meets"),
                            (3, "3 - Meets"),
                            (4, "4 - Exceeds"),
                            (5, "5 - Outstanding"),
                        ],
                        null=True,
                    ),
                ),
                ("self_comment", models.TextField(blank=True, null=True)),
                (
                    "evidence",
                    models.FileField(
                        blank=True, null=True, upload_to="performance/evidence/"
                    ),
                ),
                (
                    "manager_rating",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[
                            (1, "1 - Below expectations"),
                            (2, "2 - Partially meets"),
                            (3, "3 - Meets"),
                            (4, "4 - Exceeds"),
                            (5, "5 - Outstanding"),
                        ],
                        null=True,
                    ),
                ),
                ("manager_comment", models.TextField(blank=True, null=True)),
                (
                    "revision_note",
                    models.CharField(
                        blank=True,
                        help_text="Reason when the goal is changed after approval",
                        max_length=250,
                        null=True,
                    ),
                ),
                (
                    "sheet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="goals",
                        to="PerformanceManagement.goalsheet",
                    ),
                ),
                (
                    "kpi",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="goals",
                        to="PerformanceManagement.kpi",
                    ),
                ),
            ],
            options={
                "ordering": ["sheet", "id"],
            },
        ),
        migrations.CreateModel(
            name="PerformanceImprovementPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("objectives", models.TextField()),
                ("support_plan", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("extended", "Extended"),
                            ("completed", "Completed - improved"),
                            ("failed", "Completed - not improved"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("outcome_notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pips",
                        to="EmpManagement.emp_master",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pips_owned",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sheet",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pips",
                        to="PerformanceManagement.goalsheet",
                    ),
                ),
            ],
            options={
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="PIPReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("review_date", models.DateField(default=django.utils.timezone.now)),
                ("progress_notes", models.TextField()),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[
                            (1, "1 - Below expectations"),
                            (2, "2 - Partially meets"),
                            (3, "3 - Meets"),
                            (4, "4 - Exceeds"),
                            (5, "5 - Outstanding"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "pip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="PerformanceManagement.performanceimprovementplan",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-review_date"],
            },
        ),
        migrations.CreateModel(
            name="IncrementBand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "1 - Below expectations"),
                            (2, "2 - Partially meets"),
                            (3, "3 - Meets"),
                            (4, "4 - Exceeds"),
                            (5, "5 - Outstanding"),
                        ]
                    ),
                ),
                (
                    "increment_percent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "bonus_months",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Bonus as months of basic salary",
                        max_digits=4,
                    ),
                ),
                (
                    "guideline_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Target share of employees for calibration",
                        max_digits=5,
                    ),
                ),
                (
                    "cycle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="increment_bands",
                        to="PerformanceManagement.appraisalcycle",
                    ),
                ),
            ],
            options={
                "ordering": ["cycle", "-rating"],
                "unique_together": {("cycle", "rating")},
            },
        ),
    ]
