# Generated by Django 5.2.17 on 2026-10-07 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CourseModule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("course_id", models.IntegerField(db_index=True)),
                ("title", models.CharField(max_length=200)),
                ("order", models.PositiveIntegerField(default=1)),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("video", "Video"),
                            ("document", "Document"),
                            ("link", "Link"),
                            ("quiz", "Quiz"),
                        ],
                        default="video",
                        max_length=10,
                    ),
                ),
                ("url", models.URLField(blank=True, null=True)),
                (
                    "file",
                    models.FileField(
                        blank=True, null=True, upload_to="learning/modules/"
                    ),
                ),
                ("duration_minutes", models.PositiveIntegerField(default=10)),
                (
                    "pass_mark",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Quiz only; empty = course pass mark",
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["course_id", "order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Provider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                (
                    "contact_person",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("phone", models.CharField(blank=True, max_length=40, null=True)),
                (
                    "trn",
                    models.CharField(
                        blank=True,
                        help_text="UAE VAT tax registration number (15 digits)",
                        max_length=20,
                        null=True,
                        verbose_name="TRN",
                    ),
                ),
                ("website", models.URLField(blank=True, null=True)),
                (
                    "accreditation",
                    models.CharField(
                        blank=True,
                        help_text="e.g. KHDA, ADEK, DOH, CIPD approved",
                        max_length=200,
                        null=True,
                    ),
                ),
                ("contract_expiry", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SessionCost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_id", models.IntegerField(db_index=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("trainer_fee", "Trainer fee"),
                            ("venue", "Venue"),
                            ("material", "Material"),
                            ("travel", "Travel"),
                            ("other", "Other"),
                        ],
                        default="trainer_fee",
                        max_length=12,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "description",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("invoice_ref", models.CharField(blank=True, max_length=60, null=True)),
            ],
            options={
                "ordering": ["session_id", "id"],
            },
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        help_text="e.g. Technical, Safety, Soft skill",
                        max_length=80,
                        null=True,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="SkillLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("level", models.PositiveSmallIntegerField(unique=True)),
                ("label", models.CharField(max_length=40)),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "ordering": ["level"],
            },
        ),
        migrations.CreateModel(
            name="TrainingCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=30, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name_plural": "training categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Venue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("location", models.CharField(blank=True, max_length=200, null=True)),
                ("capacity", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "cost_per_day",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="AlertLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kind", models.CharField(max_length=20)),
                ("ref_id", models.IntegerField()),
                ("key", models.CharField(max_length=20)),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                ("recipients", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "unique_together": {("kind", "ref_id", "key")},
            },
        ),
        migrations.CreateModel(
            name="OnlineEnrolment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("course_id", models.IntegerField(db_index=True)),
                ("employee_id", models.IntegerField(db_index=True)),
                ("enrolled_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("score", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("enrolled", "Enrolled"),
                            ("in_progress", "In progress"),
                            ("completed", "Completed"),
                            ("failed", "Not passed"),
                        ],
                        default="enrolled",
                        max_length=12,
                    ),
                ),
                (
                    "nomination_id",
                    models.IntegerField(
                        blank=True,
                        help_text="Set when the course is part of a session nomination",
                        null=True,
                    ),
                ),
                ("certificate_id", models.IntegerField(blank=True, null=True)),
                (
                    "assigned_by",
                    models.IntegerField(blank=True, help_text="user id", null=True),
                ),
            ],
            options={
                "ordering": ["-enrolled_at"],
                "unique_together": {("course_id", "employee_id")},
            },
        ),
        migrations.CreateModel(
            name="SessionAttendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_id", models.IntegerField(db_index=True)),
                ("nomination_id", models.IntegerField(db_index=True)),
                ("date", models.DateField()),
                ("present", models.BooleanField(default=True)),
                (
                    "hours",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("remarks", models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                "ordering": ["session_id", "date"],
                "unique_together": {("nomination_id", "date")},
            },
        ),
        migrations.CreateModel(
            name="Trainer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "trainer_type",
                    models.CharField(
                        choices=[
                            ("internal", "Internal (employee)"),
                            ("external", "External"),
                        ],
                        default="external",
                        max_length=10,
                    ),
                ),
                (
                    "employee_id",
                    models.IntegerField(
                        blank=True,
                        help_text="emp_master id for internal trainers",
                        null=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="External trainer name (internal: filled from the employee)",
                        max_length=150,
                        null=True,
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("phone", models.CharField(blank=True, max_length=40, null=True)),
                ("expertise", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "rate_per_hour",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "rate_per_day",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "provider",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="trainers",
                        to="LearningPlus.provider",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="TrainingBudget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveIntegerField()),
                (
                    "department_id",
                    models.IntegerField(
                        blank=True, help_text="Empty = company-wide budget", null=True
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("notes", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "ordering": ["-year", "department_id"],
                "unique_together": {("year", "department_id")},
            },
        ),
        migrations.CreateModel(
            name="CourseExtra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("course_id", models.IntegerField(unique=True)),
                (
                    "delivery",
                    models.CharField(
                        choices=[
                            ("classroom", "Classroom"),
                            ("online", "Online"),
                            ("blended", "Blended"),
                        ],
                        default="classroom",
                        max_length=10,
                    ),
                ),
                ("language", models.CharField(default="English", max_length=40)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                            ("expert", "Expert"),
                        ],
                        default="beginner",
                        max_length=15,
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="courses",
                        to="LearningPlus.provider",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="courses",
                        to="LearningPlus.trainingcategory",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SessionExtra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_id", models.IntegerField(unique=True)),
                (
                    "other_costs",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Lump sum not itemised in cost lines",
                        max_digits=12,
                    ),
                ),
                ("notes", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "provider",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sessions",
                        to="LearningPlus.provider",
                    ),
                ),
                (
                    "trainer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sessions",
                        to="LearningPlus.trainer",
                    ),
                ),
                (
                    "venue",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sessions",
                        to="LearningPlus.venue",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ModuleProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("employee_id", models.IntegerField(db_index=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not started"),
                            ("in_progress", "In progress"),
                            ("completed", "Completed"),
                        ],
                        default="not_started",
                        max_length=12,
                    ),
                ),
                ("progress", models.PositiveSmallIntegerField(default=0)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("score", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("passed", models.BooleanField(blank=True, null=True)),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress",
                        to="LearningPlus.coursemodule",
                    ),
                ),
            ],
            options={
                "unique_together": {("employee_id", "module")},
            },
        ),
        migrations.CreateModel(
            name="RoleSkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("designation_id", models.IntegerField(db_index=True)),
                ("required_level", models.PositiveSmallIntegerField(default=3)),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roles",
                        to="LearningPlus.skill",
                    ),
                ),
            ],
            options={
                "unique_together": {("designation_id", "skill")},
            },
        ),
        migrations.CreateModel(
            name="EmployeeSkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("employee_id", models.IntegerField(db_index=True)),
                ("level", models.PositiveSmallIntegerField(default=1)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("course", "Course passed"),
                            ("online", "Online course"),
                            ("manual", "Manual"),
                            ("appraisal", "Appraisal"),
                        ],
                        default="manual",
                        max_length=10,
                    ),
                ),
                ("source_ref", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "verified_by",
                    models.IntegerField(blank=True, help_text="user id", null=True),
                ),
                ("date", models.DateField(blank=True, null=True)),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employees",
                        to="LearningPlus.skill",
                    ),
                ),
            ],
            options={
                "ordering": ["employee_id", "skill"],
                "unique_together": {("employee_id", "skill")},
            },
        ),
        migrations.CreateModel(
            name="CourseSkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("course_id", models.IntegerField(db_index=True)),
                ("level_gained", models.PositiveSmallIntegerField(default=2)),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="courses",
                        to="LearningPlus.skill",
                    ),
                ),
            ],
            options={
                "unique_together": {("course_id", "skill")},
            },
        ),
    ]
