# Generated by Django 5.2.17 on 2026-10-06 08:17

import django.core.validators
import django.db.models.deletion
import tenant_users.permissions.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("schema_name", models.SlugField(blank=True, null=True, unique=True)),
                ("paid_until", models.DateField(auto_now_add=True)),
                ("created_on", models.DateField(auto_now_add=True)),
                ("logo", models.ImageField(blank=True, null=True, upload_to="")),
                (
                    "employer_unique_id",
                    models.CharField(
                        blank=True,
                        help_text="13-digit Employer Unique ID from Ministry of Labor",
                        max_length=13,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\d{13}$", "Must be a 13-digit number"
                            )
                        ],
                    ),
                ),
                (
                    "bank_routing_code",
                    models.CharField(
                        blank=True,
                        help_text="9-digit bank routing code for employer's corporate account",
                        max_length=9,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\d{9}$", "Must be a 9-digit number"
                            )
                        ],
                    ),
                ),
                (
                    "industry_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("IT", "Information Technology"),
                            ("HC", "Healthcare"),
                            ("FIN", "Finance"),
                            ("EDU", "Education"),
                            ("MFG", "Manufacturing"),
                            ("RET", "Retail"),
                            ("OTH", "Other"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "address_line1",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "address_line2",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("financial_year", models.DateField(blank=True, null=True)),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("timezone", models.CharField(blank=True, max_length=50, null=True)),
                ("pincode", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Core.cntry_mstr",
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Core.crncy_mstr",
                    ),
                ),
                (
                    "state",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Core.state_mstr",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Domain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "domain",
                    models.CharField(db_index=True, max_length=253, unique=True),
                ),
                ("is_primary", models.BooleanField(db_index=True, default=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="domains",
                        to="UserManagement.company",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(default=False, verbose_name="verified"),
                ),
                ("username", models.CharField(max_length=150, unique=True)),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        unique=True,
                        verbose_name="Email Address",
                    ),
                ),
                ("is_ess", models.BooleanField(blank=True, default=False, null=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_superuser", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("otp", models.CharField(blank=True, max_length=6, null=True)),
                ("otp_created_at", models.DateTimeField(blank=True, null=True)),
                ("is_2fa_verified", models.BooleanField(default=False)),
                ("timezone", models.CharField(blank=True, max_length=50, null=True)),
                ("must_change_password", models.BooleanField(default=False)),
                (
                    "tenants",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The tenants this user belongs to.",
                        related_name="user_set",
                        to="UserManagement.company",
                        verbose_name="tenants",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(
                models.Model,
                tenant_users.permissions.models.PermissionsMixinFacade,
            ),
        ),
        migrations.CreateModel(
            name="UserNotificationInbox",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("schema_name", models.CharField(max_length=100)),
                ("branch_id", models.IntegerField(blank=True, null=True)),
                (
                    "branch_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("general", "General"),
                            ("request", "Request"),
                            ("doc_request", "Document Request"),
                            ("resignation", "Resignation"),
                            ("late_early", "Late/Early"),
                            ("loan", "Loan"),
                            ("advance_salary", "Advance Salary"),
                        ],
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("message", models.TextField()),
                ("source_model", models.CharField(max_length=100)),
                ("source_id", models.IntegerField()),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_inbox",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
