
"""
Django settings for zeo project.

Generated by 'django-admin startproject' using Django 5.0.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
from pathlib import Path
from datetime import timedelta
from celery import Celery
from celery.schedules import crontab
import os
# from tenant_schemas.middleware import DefaultTenantMiddleware
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# v1.13.1: server-specific values and secrets come from the environment or from a `.env` file next to manage.py
# (see .env.example). Nothing secret is kept in this file.
def _load_env_file(path):
    try:
        with open(path, encoding='utf-8') as fh:
            for raw in fh:
                line = raw.strip()
                if not line or line.startswith('#') or '=' not in line:
                    continue
                k, v = line.split('=', 1)
                k, v = k.strip(), v.strip()
                if len(v) >= 2 and v[0] == v[-1] and v[0] in '"\'':
                    v = v[1:-1]
                os.environ.setdefault(k, v)
    except FileNotFoundError:
        pass


_load_env_file(BASE_DIR / '.env')


def env(name, default=''):
    return os.environ.get(name, default)


def env_bool(name, default=False):
    v = os.environ.get(name)
    return default if v is None else v.strip().lower() in ('1', 'true', 'yes', 'on')


def env_list(name, default=()):
    v = os.environ.get(name)
    return [x.strip() for x in v.split(',') if x.strip()] if v else list(default)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-bu8sj-dd80ca20luk_(bo_tho55@wtmlpy^9k9gun$!f8&z4)&'
if not SECRET_KEY:
    raise RuntimeError('Set ZEO_SECRET_KEY in the environment or in .env (see .env.example).')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool('ZEO_DEBUG', False)

CORS_ALLOW_CREDENTIALS = True
ALLOWED_HOSTS = ['80.65.208.178', 'localhost', '127.0.0.1','discharge-doctrine-superman.ngrok-free.dev']

SHARED_APPS = [
    'django_tenants',
    "tenant_users.permissions",
    "tenant_users.tenants",
    "tenant_users",
    'UserManagement',
    'Core',
    'rest_framework',
    # 'rest_framework_simplejwt.token_blacklist',
    'channels',
    'django.contrib.contenttypes',
    'django.contrib.auth',
    'django.contrib.sessions',
    'django.contrib.sites',
    'django.contrib.messages',
    'django.contrib.admin',
    'django.contrib.staticfiles',
    'rest_framework.authtoken',
    'import_export',
    'django_celery_beat',
    'oauth2_provider',
    'corsheaders',
]

TENANT_APPS = [
    # "tenant_users.permissions",
    'OrganisationManager',
    'EmpManagement',
    'calendars',
    'PayrollManagement',
    'ProjectManagement',
    'PerformanceManagement',
    'RecruitmentManagement',
    'LearningManagement',
    'DashboardManagement',
    'AccessControl',
    'DataTools',
    'LeavePolicy',
    'HRActions',
    'ExpenseManagement',
    'ProjectControl',
    'LearningPlus',
    'Chatter',
    'OrgStructure',      # v1.12.0 organisation structure (locations, divisions, sections, cost centres, grades, positions…)
    'ShiftPlanner',      # v1.12.0 shift planner (rosters, requests, open shifts, availability)
    'AttendancePlus',    # v1.12.0 attendance rules, methods, devices, corrections
    'AssetPlus',         # v1.12.0 asset life cycle
    'EmployeeProfile',   # v1.13.0 employee master extras (UAE identity, emergency contacts, employment / probation, code numbering)
    'SelfService',       # v1.13.0 employee self service (change requests, HR letters, complaints, field policy)
    'django.contrib.admin',

]

# INSTALLED_APPS = list(set(SHARED_APPS + TENANT_APPS))
INSTALLED_APPS = SHARED_APPS + [app for app in TENANT_APPS if app not in SHARED_APPS]
SITE_ID = 1
TENANT_SCHEMA_DEFAULT ='public'
TENANT_MODEL = "UserManagement.company" # app.Model
TENANT_DOMAIN_MODEL = "UserManagement.Domain"  # app.Model
TENANT_USERS_DOMAIN = "localhost"
PUBLIC_SCHEMA_NAME = 'public'

# DEFAULT_FILE_STORAGE = 'tenant_schemas.storage.TenantFileSystemStorage'
DATABASE_ROUTERS = (
    'django_tenants.routers.TenantSyncRouter',
)
PG_EXTRA_SEARCH_PATHS = ['extensions']
SESSION_COOKIE_DOMAIN = '.zeo.com'
SESSION_COOKIE_SECURE = True
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '%(levelname)s %(asctime)s %(module)s %(message)s',
        },
    },
    'handlers': {
        'console': {
            'level': 'DEBUG',  # Set to DEBUG to capture all messages
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        '': {  # Root logger - will capture all logs
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': True,
        },
    },
}

CORS_ALLOWED_ORIGINS = [
    "http://localhost:4200",  # Angular app running locally
    "http://80.65.208.178:4200",  # Example for your frontend URL
#    "http://80.65.208.178",  # Your server IP if accessing directly

]

CORS_ALLOW_HEADERS = [
    'content-type',
    'Authorization',  # Add this if you're using authorization headers
]


CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]
MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',  # Optional for trailing slash handling
    'django.middleware.security.SecurityMiddleware',
#    'corsheaders.middleware.CorsMiddleware',  # Ensure this is before CommonMiddleware
#    'django.middleware.common.CommonMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'UserManagement.middleware.SchemaMiddleware',  # Your custom schema middleware
    'UserManagement.middleware.TenantTimezoneMiddleware',  # Your timezone middleware
    'Chatter.tracking.CurrentRequestMiddleware',  # change history: who made each change
]


SESSION_ENGINE = 'django.contrib.sessions.backends.db'
CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': env('ZEO_REDIS_CACHE_URL', 'redis://127.0.0.1:6379/1'),
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
        }
    }
}
if env('ZEO_REDIS_CACHE_URL') == 'locmem':   # v1.13.1: no Redis (small / test servers) – cache in memory
    CACHES = {'default': {'BACKEND': 'django.core.cache.backends.locmem.LocMemCache'}}

ROOT_URLCONF = 'zeo.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]
TEMPLATE_CONTEXT_PROCESSORS = (
    'django.core.context_processors.request',
    #...
)

WSGI_APPLICATION = 'zeo.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django_tenants.postgresql_backend',
        'NAME': 'zeo', 
        'USER': 'zeo_user', 
        'PASSWORD': '1234',
        'HOST': '127.0.0.1', 
        'PORT': '5432',
    }
}




# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")


# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = "UserManagement.CustomUser"

AUTHENTICATION_BACKENDS = [
    

    'UserManagement.authentication.CustomAuthBackend',
    'django.contrib.auth.backends.ModelBackend',
]
#auth and permissions
#auth and permissions
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        # 'oauth2_provider.contrib.rest_framework.OAuth2Authentication',
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        # 'rest_framework.permissions.IsAuthenticated',
    ),
    'EXCEPTION_HANDLER': 'zeo.exceptions.custom_exception_handler',

}

REST_USE_JWT = True
SIMPLE_JWT = {
    # Customize token settings if needed
    "ACCESS_TOKEN_LIFETIME": timedelta(hours=24),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=14),
}

SHOW_PUBLIC_IF_NO_TENANT_FOUND = True
#https://github.com/microsoftarchive/redis/releases
# Celery settings
#redis automatic  -redis-server --service-install redis.windows.conf --loglevel verbose
#redis-server --service-start
CELERY_BROKER_URL = env('ZEO_CELERY_BROKER_URL', 'redis://localhost:6379/0')
CELERY_RESULT_BACKEND = env('ZEO_CELERY_RESULT_BACKEND', CELERY_BROKER_URL)
# Set this to ensure retries during startup
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True

CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
TIME_ZONE = 'UTC'  # or your specific timezone
CELERY_TIMEZONE = 'Asia/Kolkata'  # or your specific timezone
CELERY_ENABLE_UTC = True  # Ensure UTC is enabled if needed

CELERY_BEAT_SCHEDULE = {
    'schedule-document-expiry-notifications-for-all-tenants': {
        'task': 'EmpManagement.tasks.send_document_expiry_notifications_for_all_tenants',
        'schedule': crontab(hour=12, minute=00) 
        # 'schedule': timedelta(days=1)1744,

    },
    'accrue-leaves-every-day': {
        'task': 'calendars.tasks.accrue_leaves',  # Use the correct path to your task
        'schedule': crontab(hour=17, minute=45),  
    },
    'reset-leave-month':{
        'task':'calendars.tasks.reset_leave_balances',
        'schedule':crontab(hour=17, minute=55)
    },
    'deduct_expired_carry_forward_leaves_daily': {
        'task': 'calendars.tasks.deduct_expired_carry_forward_leaves',
        'schedule': crontab(hour=12, minute=00),  # Runs daily at midnight
    },
    # v1.11.0: leave policies – leave-year end and monthly accrual on the 1st, compensatory off expiry daily
    'leave-policy-daily-jobs': {
        'task': 'LeavePolicy.tasks.leave_daily_jobs',
        'schedule': crontab(hour=1, minute=10),
    },
    # v1.11.0: leave approval escalation (it was set up per level but never ran)
    'leave-approval-escalations': {
        'task': 'LeavePolicy.tasks.leave_escalations',
        'schedule': crontab(minute='*/15'),
    },
    # v1.11.0: training certificate expiry alerts and nomination reminders
    'learning-certificate-expiry-alerts': {'task': 'LearningPlus.tasks.certificate_expiry_alerts', 'schedule': crontab(hour=7, minute=5)},
    'learning-nomination-escalations': {'task': 'LearningPlus.tasks.nomination_escalations', 'schedule': crontab(hour=8, minute=5)},
    # v1.12.0
    'shift-reminders-daily': {'task': 'ShiftPlanner.tasks.shift_reminders', 'schedule': crontab(hour=14, minute=5)},
    'attendance-plus-nightly': {'task': 'AttendancePlus.tasks.attendance_nightly', 'schedule': crontab(hour=2, minute=15)},
    'attendance-plus-missing-punch': {'task': 'AttendancePlus.tasks.missing_punch_check', 'schedule': crontab(minute=20)},
    'asset-daily-reminders': {'task': 'AssetPlus.tasks.asset_daily_reminders', 'schedule': crontab(hour=7, minute=20)},
    'orgstructure-policy-reminders': {'task': 'OrgStructure.tasks.remind_unacknowledged_policies', 'schedule': crontab(hour=7, minute=10)},
    # v1.13.0
    'employeeprofile-probation-reminders': {'task': 'EmployeeProfile.tasks.probation_reminders', 'schedule': crontab(hour=7, minute=25)},
    'ess-escalate-complaints': {'task': 'SelfService.tasks.escalate_complaints', 'schedule': crontab(hour=6, minute=15)},
}
# CELERY_BEAT_SCHEDULE_FILENAME = 'celerybeat-schedule'  # Save Celery Beat schedule state

CELERY_IMPORTS = ('EmpManagement.tasks',)


#default email settings
# Fallback sender (each company can also set its own mail server under Settings → E-mail configuration).
EMAIL_HOST = env('ZEO_EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(env('ZEO_EMAIL_PORT', '587'))
EMAIL_USE_TLS = env_bool('ZEO_EMAIL_USE_TLS', True)
EMAIL_HOST_USER = env('ZEO_EMAIL_USER')
EMAIL_HOST_PASSWORD = env('ZEO_EMAIL_PASSWORD')
DEFAULT_FROM_EMAIL = env('ZEO_DEFAULT_FROM_EMAIL', EMAIL_HOST_USER or 'webmaster@localhost')
# without a mail account, e-mails are written to the log instead of failing
EMAIL_BACKEND = env('ZEO_EMAIL_BACKEND', 'django.core.mail.backends.smtp.EmailBackend' if EMAIL_HOST_USER else 'django.core.mail.backends.console.EmailBackend')

