# Generated by Django 5.2.17 on 2026-10-07 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CostCenter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=30, unique=True)),
                ("name", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True, default="")),
                ("active", models.BooleanField(default=True)),
                (
                    "branch_ids",
                    models.JSONField(
                        blank=True, default=list, help_text="[] = all branches"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by_id", models.IntegerField(blank=True, null=True)),
                ("department_id", models.IntegerField(blank=True, null=True)),
                (
                    "manager_id",
                    models.IntegerField(blank=True, help_text="employee id", null=True),
                ),
                (
                    "expense_cost_center_id",
                    models.IntegerField(
                        blank=True,
                        help_text="ExpenseManagement.CostCenter kept in step",
                        null=True,
                    ),
                ),
            ],
            options={
                "ordering": ["code"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CountryPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=150)),
                (
                    "country_code",
                    models.CharField(
                        help_text="ISO 3166 alpha-2, e.g. AE", max_length=2
                    ),
                ),
                ("country_name", models.CharField(max_length=80)),
                (
                    "law_reference",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                (
                    "weekend_days",
                    models.JSONField(
                        blank=True, default=list, help_text="0=Mon … 6=Sun"
                    ),
                ),
                (
                    "daily_hours",
                    models.DecimalField(decimal_places=2, default=8, max_digits=4),
                ),
                (
                    "weekly_hours",
                    models.DecimalField(decimal_places=2, default=48, max_digits=5),
                ),
                (
                    "ramadan_daily_hours",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                (
                    "annual_leave",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='{"first_year_after_months": 6, "first_year_days_per_month": 2, "days": 30, "steps": [{"after_years": 5, "days": 30}], "basis": "calendar"}',
                    ),
                ),
                (
                    "sick_leave",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="[[days, pay %], ...] in order",
                    ),
                ),
                (
                    "maternity",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='{"days": 60, "full_pay_days": 45, "half_pay_days": 15}',
                    ),
                ),
                ("paternity_days", models.PositiveIntegerField(default=0)),
                (
                    "gratuity",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='{"basis": "basic", "slabs": [{"from_year": 1, "to_year": 5, "days": 21}], "cap_years_of_pay": 2, "min_service_years": 1, "by_contract": {...}}',
                    ),
                ),
                (
                    "overtime",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='{"normal": 125, "night": 150, "rest_day": 150, "holiday": 150, "max_hours_per_day": 2}',
                    ),
                ),
                (
                    "notice_period",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='{"min_days": 30, "max_days": 90}',
                    ),
                ),
                ("probation_max_months", models.PositiveIntegerField(default=6)),
                (
                    "public_holiday_source",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("wps_notes", models.TextField(blank=True, default="")),
                ("notes", models.TextField(blank=True, default="")),
                ("active", models.BooleanField(default=True)),
                (
                    "is_standard",
                    models.BooleanField(
                        default=False, help_text="loaded from the standard GCC set"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "country policies",
                "ordering": ["country_name", "code"],
            },
        ),
        migrations.CreateModel(
            name="Division",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=30, unique=True)),
                ("name", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True, default="")),
                ("active", models.BooleanField(default=True)),
                (
                    "branch_ids",
                    models.JSONField(
                        blank=True, default=list, help_text="[] = all branches"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by_id", models.IntegerField(blank=True, null=True)),
                ("head_employee_id", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "ordering": ["code"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EmploymentType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=30, unique=True)),
                ("name", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True, default="")),
                ("active", models.BooleanField(default=True)),
                (
                    "branch_ids",
                    models.JSONField(
                        blank=True, default=list, help_text="[] = all branches"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by_id", models.IntegerField(blank=True, null=True)),
                ("counts_for_gratuity", models.BooleanField(default=True)),
                ("probation_days", models.PositiveIntegerField(default=0)),
                (
                    "has_end_date",
                    models.BooleanField(
                        default=False,
                        help_text="contract / temporary: an end date is expected",
                    ),
                ),
            ],
            options={
                "ordering": ["code"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Grade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=30, unique=True)),
                ("name", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True, default="")),
                ("active", models.BooleanField(default=True)),
                (
                    "branch_ids",
                    models.JSONField(
                        blank=True, default=list, help_text="[] = all branches"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by_id", models.IntegerField(blank=True, null=True)),
                ("level", models.IntegerField(default=1, help_text="rank, 1 = lowest")),
                (
                    "salary_min",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "salary_max",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("currency", models.CharField(default="AED", max_length=3)),
                (
                    "designation_ids",
                    models.JSONField(
                        blank=True, default=list, help_text="[] = any designation"
                    ),
                ),
                ("benefits", models.TextField(blank=True, default="")),
            ],
            options={
                "ordering": ["level", "code"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=30, unique=True)),
                ("name", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True, default="")),
                ("active", models.BooleanField(default=True)),
                (
                    "branch_ids",
                    models.JSONField(
                        blank=True, default=list, help_text="[] = all branches"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by_id", models.IntegerField(blank=True, null=True)),
                ("address", models.TextField(blank=True, default="")),
                ("city", models.CharField(blank=True, default="", max_length=80)),
                (
                    "country_id",
                    models.IntegerField(
                        blank=True, help_text="Core.cntry_mstr", null=True
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
            ],
            options={
                "ordering": ["code"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OrgSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("use_locations", models.BooleanField(default=False)),
                ("use_divisions", models.BooleanField(default=False)),
                ("use_sections", models.BooleanField(default=False)),
                ("use_cost_centers", models.BooleanField(default=False)),
                (
                    "use_employee_categories",
                    models.BooleanField(
                        default=True,
                        help_text="off = category hidden everywhere (data and leave-policy mapping are kept)",
                    ),
                ),
                ("use_grades", models.BooleanField(default=False)),
                ("use_job_positions", models.BooleanField(default=False)),
                ("use_employment_types", models.BooleanField(default=False)),
                (
                    "labels",
                    models.JSONField(
                        blank=True, default=dict, help_text='{"sections": "Unit", ...}'
                    ),
                ),
                (
                    "mandatory",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='{"sections": true, ...} on the employee form',
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("updated_by_id", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "organisation settings",
                "verbose_name_plural": "organisation settings",
            },
        ),
        migrations.CreateModel(
            name="PolicyVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("policy_id", models.IntegerField(unique=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "fingerprint",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                ("requires_ack", models.BooleanField(default=True)),
                (
                    "due_days",
                    models.PositiveIntegerField(
                        default=7, help_text="days to acknowledge before reminders"
                    ),
                ),
                ("version_date", models.DateTimeField(blank=True, null=True)),
                ("last_reminded_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=30, unique=True)),
                ("name", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True, default="")),
                ("active", models.BooleanField(default=True)),
                (
                    "branch_ids",
                    models.JSONField(
                        blank=True, default=list, help_text="[] = all branches"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by_id", models.IntegerField(blank=True, null=True)),
                (
                    "department_id",
                    models.IntegerField(help_text="OrganisationManager.dept_master"),
                ),
                ("head_employee_id", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "ordering": ["code"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BranchCountryPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("branch_id", models.IntegerField(unique=True)),
                ("applied_at", models.DateTimeField(auto_now=True)),
                ("applied_by_id", models.IntegerField(blank=True, null=True)),
                (
                    "country_policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="branches",
                        to="OrgStructure.countrypolicy",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DivisionDepartment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("department_id", models.IntegerField(unique=True)),
                (
                    "division",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="departments",
                        to="OrgStructure.division",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JobPosition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=30, unique=True)),
                ("name", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True, default="")),
                ("active", models.BooleanField(default=True)),
                (
                    "branch_ids",
                    models.JSONField(
                        blank=True, default=list, help_text="[] = all branches"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by_id", models.IntegerField(blank=True, null=True)),
                ("department_id", models.IntegerField(blank=True, null=True)),
                ("designation_id", models.IntegerField(blank=True, null=True)),
                ("headcount_budget", models.PositiveIntegerField(default=1)),
                (
                    "grade",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="positions",
                        to="OrgStructure.grade",
                    ),
                ),
                (
                    "reports_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="children",
                        to="OrgStructure.jobposition",
                    ),
                ),
            ],
            options={
                "ordering": ["code"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PolicyAcknowledgement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("policy_id", models.IntegerField(db_index=True)),
                ("employee_id", models.IntegerField(db_index=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("acknowledged_at", models.DateTimeField(auto_now_add=True)),
                ("ip", models.CharField(blank=True, default="", max_length=60)),
                ("user_id", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-acknowledged_at"],
                "unique_together": {("policy_id", "employee_id", "version")},
            },
        ),
        migrations.CreateModel(
            name="EmployeeOrg",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("employee_id", models.IntegerField(unique=True)),
                ("contract_end_date", models.DateField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("updated_by_id", models.IntegerField(blank=True, null=True)),
                (
                    "cost_center",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="OrgStructure.costcenter",
                    ),
                ),
                (
                    "division",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="OrgStructure.division",
                    ),
                ),
                (
                    "employment_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="OrgStructure.employmenttype",
                    ),
                ),
                (
                    "grade",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="OrgStructure.grade",
                    ),
                ),
                (
                    "job_position",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="holders",
                        to="OrgStructure.jobposition",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="OrgStructure.location",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="OrgStructure.section",
                    ),
                ),
            ],
        ),
    ]
