# Generated by Django 5.2.17 on 2026-10-07 20:35

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Availability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("employee_id", models.IntegerField(db_index=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("unavailable", "Unavailable"),
                            ("preferred", "Preferred"),
                        ],
                        default="unavailable",
                        max_length=12,
                    ),
                ),
                (
                    "weekday",
                    models.IntegerField(
                        blank=True,
                        help_text="0 = Monday … 6 = Sunday (repeats every week)",
                        null=True,
                    ),
                ),
                ("date_from", models.DateField(blank=True, null=True)),
                ("date_to", models.DateField(blank=True, null=True)),
                (
                    "shift_id",
                    models.IntegerField(
                        blank=True,
                        help_text="preferred / available for this shift only",
                        null=True,
                    ),
                ),
                ("note", models.CharField(blank=True, default="", max_length=255)),
                ("created_by_id", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["employee_id", "weekday", "date_from"],
            },
        ),
        migrations.CreateModel(
            name="OpenShift",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("shift_id", models.IntegerField()),
                ("branch_id", models.IntegerField(db_index=True)),
                ("department_id", models.IntegerField(blank=True, null=True)),
                ("slots", models.PositiveIntegerField(default=1)),
                ("note", models.CharField(blank=True, default="", max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("filled", "Filled"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="open",
                        max_length=10,
                    ),
                ),
                ("created_by_id", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="RosterPeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("branch_id", models.IntegerField(db_index=True)),
                ("department_id", models.IntegerField(blank=True, null=True)),
                ("date_from", models.DateField()),
                ("date_to", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("approved", "Approved"),
                            ("published", "Published"),
                            ("rejected", "Sent back"),
                        ],
                        default="draft",
                        max_length=10,
                    ),
                ),
                (
                    "approver_id",
                    models.IntegerField(
                        blank=True,
                        help_text="user who approves this roster (optional)",
                        null=True,
                    ),
                ),
                (
                    "default_shift_id",
                    models.IntegerField(
                        blank=True,
                        help_text="shift for working days of employees without a shift schedule",
                        null=True,
                    ),
                ),
                (
                    "min_rest_hours",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("8"), max_digits=5
                    ),
                ),
                (
                    "max_week_hours",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("48"), max_digits=5
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "decision_note",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("created_by_id", models.IntegerField(blank=True, null=True)),
                ("submitted_by_id", models.IntegerField(blank=True, null=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("approved_by_id", models.IntegerField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("published_by_id", models.IntegerField(blank=True, null=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-date_from", "-id"],
                "permissions": [
                    ("approve_rosterperiod", "Can approve shift rosters"),
                    ("publish_rosterperiod", "Can publish shift rosters"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ShiftNotice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.IntegerField(blank=True, db_index=True, null=True)),
                (
                    "employee_id",
                    models.IntegerField(blank=True, db_index=True, null=True),
                ),
                ("kind", models.CharField(max_length=20)),
                ("title", models.CharField(max_length=120)),
                ("message", models.TextField()),
                (
                    "ref",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="e.g. reminder:2026-10-09 – stops sending the same notice twice",
                        max_length=60,
                    ),
                ),
                ("emailed", models.BooleanField(default=False)),
                ("read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ShiftRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("swap", "Shift swap"),
                            ("change", "Shift change"),
                            ("cancel", "Shift cancellation"),
                        ],
                        max_length=8,
                    ),
                ),
                ("employee_id", models.IntegerField(db_index=True)),
                ("date", models.DateField()),
                (
                    "from_shift_id",
                    models.IntegerField(
                        blank=True,
                        help_text="shift on the day when the request was made (empty = day off)",
                        null=True,
                    ),
                ),
                (
                    "to_shift_id",
                    models.IntegerField(
                        blank=True,
                        help_text="shift change: the wanted shift",
                        null=True,
                    ),
                ),
                ("swap_employee_id", models.IntegerField(blank=True, null=True)),
                (
                    "swap_date",
                    models.DateField(
                        blank=True,
                        help_text="swap: the colleague's day (default the same day)",
                        null=True,
                    ),
                ),
                ("swap_shift_id", models.IntegerField(blank=True, null=True)),
                ("reason", models.CharField(blank=True, default="", max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("peer", "Waiting for colleague"),
                            ("pending", "Waiting for approval"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("declined", "Declined by colleague"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("peer_decided_at", models.DateTimeField(blank=True, null=True)),
                ("decided_by_id", models.IntegerField(blank=True, null=True)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                (
                    "decision_note",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("created_by_id", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ShiftRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("shift_id", models.IntegerField(unique=True)),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="short code used on the roster and in uploads, e.g. GEN, N1",
                        max_length=20,
                    ),
                ),
                (
                    "colour",
                    models.CharField(blank=True, default="#5b4ff5", max_length=9),
                ),
                ("active", models.BooleanField(default=True)),
                (
                    "grace_in_minutes",
                    models.PositiveIntegerField(
                        default=0, help_text="late check-in allowed without being late"
                    ),
                ),
                (
                    "grace_out_minutes",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="early check-out allowed without being early",
                    ),
                ),
                (
                    "min_hours",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="hours needed for a full day",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "max_hours",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="hours counted at most in one day",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "half_day_hours",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="hours needed for a half day",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "night_shift",
                    models.BooleanField(
                        default=False,
                        help_text="night / cross-midnight shift (set from the times unless changed by hand)",
                    ),
                ),
                (
                    "night_auto",
                    models.BooleanField(
                        default=True,
                        help_text="work out night_shift from the start and end times",
                    ),
                ),
                (
                    "ot_after_minutes",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="overtime starts this many minutes after the shift end",
                    ),
                ),
                (
                    "shift_allowance",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="paid per day worked on this shift",
                        max_digits=10,
                    ),
                ),
                (
                    "night_allowance",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="paid per night worked on this shift",
                        max_digits=10,
                    ),
                ),
                (
                    "branch_ids",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="branches that may use the shift; empty = all branches",
                    ),
                ),
                ("notes", models.CharField(blank=True, default="", max_length=255)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["shift_id"],
            },
        ),
        migrations.CreateModel(
            name="OpenShiftClaim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("employee_id", models.IntegerField(db_index=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Waiting for approval"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("note", models.CharField(blank=True, default="", max_length=255)),
                ("decided_by_id", models.IntegerField(blank=True, null=True)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                (
                    "decision_note",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "open_shift",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="claims",
                        to="ShiftPlanner.openshift",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RosterEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("employee_id", models.IntegerField(db_index=True)),
                ("date", models.DateField(db_index=True)),
                ("shift_id", models.IntegerField(blank=True, null=True)),
                ("off", models.BooleanField(default=False)),
                ("note", models.CharField(blank=True, default="", max_length=255)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("generated", "Generated"),
                            ("manual", "Edited"),
                            ("upload", "Uploaded"),
                            ("copy", "Copied"),
                            ("swap", "Swap"),
                            ("change", "Shift change"),
                            ("cancel", "Cancellation"),
                            ("open_shift", "Open shift"),
                        ],
                        default="manual",
                        max_length=12,
                    ),
                ),
                ("changed_after_publish", models.BooleanField(default=False)),
                ("updated_by_id", models.IntegerField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="ShiftPlanner.rosterperiod",
                    ),
                ),
            ],
            options={
                "ordering": ["date", "employee_id"],
                "unique_together": {("period", "employee_id", "date")},
            },
        ),
    ]
