# Generated by Django 5.2.17 on 2026-10-07 20:35

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AllocationExtra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("allocation_id", models.IntegerField(unique=True)),
                ("asset_id", models.IntegerField(db_index=True)),
                ("employee_id", models.IntegerField(db_index=True)),
                ("expected_return_date", models.DateField(blank=True, null=True)),
                ("accessories", models.CharField(blank=True, max_length=255)),
                ("handover_condition", models.CharField(blank=True, max_length=20)),
                ("handover_note", models.TextField(blank=True)),
                (
                    "handover_file",
                    models.FileField(
                        blank=True, null=True, upload_to="asset_plus/handover/"
                    ),
                ),
                ("issued_by_id", models.IntegerField(blank=True, null=True)),
                (
                    "ack_status",
                    models.CharField(
                        choices=[
                            ("pending", "Waiting for the employee"),
                            ("accepted", "Accepted"),
                            ("disputed", "Accepted with remarks"),
                            ("not_required", "Not required"),
                        ],
                        default="pending",
                        max_length=15,
                    ),
                ),
                ("ack_at", models.DateTimeField(blank=True, null=True)),
                ("ack_condition_notes", models.TextField(blank=True)),
                ("ack_by_id", models.IntegerField(blank=True, null=True)),
                ("return_reminded_on", models.DateField(blank=True, null=True)),
                ("transfer_id", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="AssetDamage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=30, unique=True)),
                ("asset_id", models.IntegerField(db_index=True)),
                (
                    "employee_id",
                    models.IntegerField(blank=True, db_index=True, null=True),
                ),
                ("allocation_id", models.IntegerField(blank=True, null=True)),
                ("description", models.TextField()),
                (
                    "responsibility",
                    models.CharField(
                        choices=[
                            ("company", "Company"),
                            ("employee", "Employee"),
                            ("shared", "Shared (employee pays part)"),
                            ("third_party", "Third party / insurance"),
                        ],
                        default="company",
                        max_length=12,
                    ),
                ),
                (
                    "recovery_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "recovery_method",
                    models.CharField(
                        choices=[
                            ("none", "No recovery"),
                            ("payroll", "Payroll deduction"),
                            ("cash", "Paid in cash"),
                            ("waived", "Waived"),
                        ],
                        default="none",
                        max_length=10,
                    ),
                ),
                ("instalments", models.PositiveSmallIntegerField(default=1)),
                (
                    "first_deduction_month",
                    models.DateField(
                        blank=True,
                        help_text="First day of the first payroll month",
                        null=True,
                    ),
                ),
                (
                    "recovered_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("reported", "Waiting for approval"),
                            ("approved", "Approved"),
                            ("recovering", "Being recovered"),
                            ("closed", "Closed"),
                            ("rejected", "Rejected"),
                        ],
                        default="reported",
                        max_length=12,
                    ),
                ),
                ("source", models.CharField(default="hr", max_length=12)),
                ("reported_by_id", models.IntegerField(blank=True, null=True)),
                ("decided_by_id", models.IntegerField(blank=True, null=True)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("decision_note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("damage_date", models.DateField()),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("minor", "Minor"),
                            ("major", "Major"),
                            ("total", "Beyond repair"),
                        ],
                        default="minor",
                        max_length=8,
                    ),
                ),
                (
                    "repair_cost",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                ("return_id", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-id"],
                "permissions": (
                    ("approve_assetdamage", "Can approve asset damage and recovery"),
                ),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AssetDisposal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=30, unique=True)),
                ("asset_id", models.IntegerField(db_index=True)),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("sale", "Sale"),
                            ("scrap", "Scrap"),
                            ("donate", "Donation"),
                            ("write_off", "Write-off"),
                        ],
                        max_length=10,
                    ),
                ),
                ("disposal_date", models.DateField()),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Sale price / scrap value received",
                        max_digits=14,
                    ),
                ),
                ("buyer", models.CharField(blank=True, max_length=150)),
                ("reason", models.TextField()),
                (
                    "book_value",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                (
                    "gain_loss",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Waiting for approval"),
                            ("approved", "Disposed"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("status_before", models.CharField(blank=True, max_length=20)),
                ("requested_by_id", models.IntegerField(blank=True, null=True)),
                ("decided_by_id", models.IntegerField(blank=True, null=True)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("decision_note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-id"],
                "permissions": (
                    ("approve_assetdisposal", "Can approve asset disposal"),
                ),
            },
        ),
        migrations.CreateModel(
            name="AssetEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("asset_id", models.IntegerField(db_index=True)),
                ("event", models.CharField(max_length=30)),
                ("summary", models.CharField(max_length=400)),
                ("changes", models.JSONField(blank=True, default=dict)),
                (
                    "employee_id",
                    models.IntegerField(blank=True, db_index=True, null=True),
                ),
                ("ref_type", models.CharField(blank=True, max_length=20)),
                ("ref_id", models.IntegerField(blank=True, null=True)),
                ("user_id", models.IntegerField(blank=True, null=True)),
                ("user_name", models.CharField(blank=True, max_length=150)),
                ("at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "ordering": ["-at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="AssetFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("asset_id", models.IntegerField(db_index=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("photo", "Photo"),
                            ("document", "Document"),
                            ("invoice", "Invoice"),
                            ("warranty", "Warranty"),
                            ("insurance", "Insurance"),
                            ("handover", "Hand-over form"),
                            ("return", "Return form"),
                            ("damage", "Damage photo"),
                            ("police_report", "Police report"),
                            ("maintenance", "Maintenance"),
                            ("disposal", "Disposal"),
                            ("other", "Other"),
                        ],
                        default="document",
                        max_length=20,
                    ),
                ),
                ("record_type", models.CharField(blank=True, max_length=20)),
                ("record_id", models.IntegerField(blank=True, null=True)),
                ("file", models.FileField(upload_to="asset_plus/files/%Y/%m/")),
                ("name", models.CharField(blank=True, max_length=255)),
                ("uploaded_by_id", models.IntegerField(blank=True, null=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-uploaded_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="AssetLoss",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=30, unique=True)),
                ("asset_id", models.IntegerField(db_index=True)),
                (
                    "employee_id",
                    models.IntegerField(blank=True, db_index=True, null=True),
                ),
                ("allocation_id", models.IntegerField(blank=True, null=True)),
                ("description", models.TextField()),
                (
                    "responsibility",
                    models.CharField(
                        choices=[
                            ("company", "Company"),
                            ("employee", "Employee"),
                            ("shared", "Shared (employee pays part)"),
                            ("third_party", "Third party / insurance"),
                        ],
                        default="company",
                        max_length=12,
                    ),
                ),
                (
                    "recovery_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "recovery_method",
                    models.CharField(
                        choices=[
                            ("none", "No recovery"),
                            ("payroll", "Payroll deduction"),
                            ("cash", "Paid in cash"),
                            ("waived", "Waived"),
                        ],
                        default="none",
                        max_length=10,
                    ),
                ),
                ("instalments", models.PositiveSmallIntegerField(default=1)),
                (
                    "first_deduction_month",
                    models.DateField(
                        blank=True,
                        help_text="First day of the first payroll month",
                        null=True,
                    ),
                ),
                (
                    "recovered_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("reported", "Waiting for approval"),
                            ("approved", "Approved"),
                            ("recovering", "Being recovered"),
                            ("closed", "Closed"),
                            ("rejected", "Rejected"),
                        ],
                        default="reported",
                        max_length=12,
                    ),
                ),
                ("source", models.CharField(default="hr", max_length=12)),
                ("reported_by_id", models.IntegerField(blank=True, null=True)),
                ("decided_by_id", models.IntegerField(blank=True, null=True)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("decision_note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("loss_date", models.DateField()),
                (
                    "kind",
                    models.CharField(
                        choices=[("lost", "Lost"), ("stolen", "Stolen")],
                        default="lost",
                        max_length=8,
                    ),
                ),
                ("place", models.CharField(blank=True, max_length=200)),
                ("police_report_no", models.CharField(blank=True, max_length=60)),
                (
                    "police_report_file",
                    models.FileField(
                        blank=True, null=True, upload_to="asset_plus/police/"
                    ),
                ),
                (
                    "investigation_status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("investigating", "Under investigation"),
                            ("closed_found", "Closed – asset found"),
                            ("closed_not_found", "Closed – not found"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                ("investigation_notes", models.TextField(blank=True)),
                ("status_before", models.CharField(blank=True, max_length=20)),
                (
                    "book_value",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                ("found_on", models.DateField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-id"],
                "permissions": (
                    (
                        "approve_assetloss",
                        "Can approve lost / stolen assets and recovery",
                    ),
                ),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AssetPlusSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("currency", models.CharField(default="AED", max_length=3)),
                ("code_padding", models.PositiveSmallIntegerField(default=4)),
                ("warranty_reminder_days", models.PositiveIntegerField(default=30)),
                (
                    "require_acknowledgement",
                    models.BooleanField(
                        default=True,
                        help_text="Employees confirm in self-service that they received the asset",
                    ),
                ),
                (
                    "block_final_settlement",
                    models.BooleanField(
                        default=True,
                        help_text="Final settlement cannot be processed while assets are still with the employee",
                    ),
                ),
                ("max_instalments", models.PositiveSmallIntegerField(default=12)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="AssetProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("asset_id", models.IntegerField(unique=True)),
                ("asset_code", models.CharField(max_length=40, unique=True)),
                (
                    "extra_status",
                    models.CharField(
                        blank=True,
                        choices=[("", "None"), ("lost", "Lost / stolen")],
                        default="",
                        max_length=12,
                    ),
                ),
                (
                    "branch_id",
                    models.IntegerField(blank=True, db_index=True, null=True),
                ),
                ("location", models.CharField(blank=True, max_length=150)),
                ("department_id", models.IntegerField(blank=True, null=True)),
                (
                    "purchase_cost",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                ("currency", models.CharField(default="AED", max_length=3)),
                ("vendor", models.CharField(blank=True, max_length=150)),
                ("invoice_no", models.CharField(blank=True, max_length=60)),
                (
                    "invoice_file",
                    models.FileField(
                        blank=True, null=True, upload_to="asset_plus/invoices/"
                    ),
                ),
                ("purchase_order", models.CharField(blank=True, max_length=60)),
                ("warranty_start", models.DateField(blank=True, null=True)),
                ("warranty_end", models.DateField(blank=True, null=True)),
                (
                    "warranty_reminder_days",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("warranty_reminded_for", models.DateField(blank=True, null=True)),
                ("insurance_provider", models.CharField(blank=True, max_length=150)),
                ("insurance_policy_no", models.CharField(blank=True, max_length=60)),
                ("insurance_expiry", models.DateField(blank=True, null=True)),
                ("insurance_reminded_for", models.DateField(blank=True, null=True)),
                (
                    "depreciation_method",
                    models.CharField(
                        choices=[
                            ("none", "No depreciation"),
                            ("straight_line", "Straight line"),
                            ("declining", "Declining balance"),
                        ],
                        default="straight_line",
                        max_length=20,
                    ),
                ),
                (
                    "depreciation_start",
                    models.DateField(
                        blank=True, help_text="Empty = purchase date", null=True
                    ),
                ),
                ("useful_life_months", models.PositiveIntegerField(default=36)),
                (
                    "salvage_value",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                (
                    "declining_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="% per year; empty = double declining (200% ÷ life in years)",
                        max_digits=6,
                        null=True,
                    ),
                ),
                ("barcode", models.CharField(blank=True, max_length=80)),
                (
                    "meter_reading",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Current km / hours",
                        max_digits=12,
                        null=True,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_by_id", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "permissions": (
                    ("view_assetbookvalue", "Can see asset cost and book value"),
                ),
            },
        ),
        migrations.CreateModel(
            name="AssetReturn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=30, unique=True)),
                ("asset_id", models.IntegerField(db_index=True)),
                ("allocation_id", models.IntegerField(blank=True, null=True)),
                ("shared_allocation_id", models.IntegerField(blank=True, null=True)),
                (
                    "employee_id",
                    models.IntegerField(blank=True, db_index=True, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("requested", "Return requested"),
                            ("completed", "Returned"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="requested",
                        max_length=10,
                    ),
                ),
                ("requested_by_id", models.IntegerField(blank=True, null=True)),
                ("request_note", models.TextField(blank=True)),
                ("preferred_date", models.DateField(blank=True, null=True)),
                ("return_date", models.DateField(blank=True, null=True)),
                (
                    "condition",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("healthy", "Healthy"),
                            ("minor_damage", "Minor damage"),
                            ("major_damage", "Major damage"),
                        ],
                        max_length=20,
                    ),
                ),
                ("accessories_returned", models.BooleanField(default=True)),
                ("missing_items", models.CharField(blank=True, max_length=255)),
                ("damage_found", models.BooleanField(default=False)),
                ("damage_description", models.TextField(blank=True)),
                (
                    "damage_estimate",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                ("damage_id", models.IntegerField(blank=True, null=True)),
                ("data_wiped", models.BooleanField(default=False)),
                ("received_by_id", models.IntegerField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="AssetTransfer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=30, unique=True)),
                ("asset_id", models.IntegerField(db_index=True)),
                (
                    "from_type",
                    models.CharField(
                        choices=[
                            ("employee", "Employee"),
                            ("location", "Location"),
                            ("department", "Department"),
                            ("store", "Store (unassigned)"),
                        ],
                        max_length=12,
                    ),
                ),
                ("from_employee_id", models.IntegerField(blank=True, null=True)),
                ("from_branch_id", models.IntegerField(blank=True, null=True)),
                ("from_location", models.CharField(blank=True, max_length=150)),
                ("from_department_id", models.IntegerField(blank=True, null=True)),
                (
                    "to_type",
                    models.CharField(
                        choices=[
                            ("employee", "Employee"),
                            ("location", "Location"),
                            ("department", "Department"),
                            ("store", "Store (unassigned)"),
                        ],
                        max_length=12,
                    ),
                ),
                ("to_employee_id", models.IntegerField(blank=True, null=True)),
                ("to_branch_id", models.IntegerField(blank=True, null=True)),
                ("to_location", models.CharField(blank=True, max_length=150)),
                ("to_department_id", models.IntegerField(blank=True, null=True)),
                ("transfer_date", models.DateField()),
                ("reason", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Waiting for approval"),
                            ("approved", "Approved"),
                            ("completed", "Completed"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=12,
                    ),
                ),
                ("requested_by_id", models.IntegerField(blank=True, null=True)),
                (
                    "requested_by_employee_id",
                    models.IntegerField(blank=True, null=True),
                ),
                ("decided_by_id", models.IntegerField(blank=True, null=True)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("decision_note", models.TextField(blank=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-id"],
                "permissions": (
                    ("approve_assettransfer", "Can approve asset transfers"),
                ),
            },
        ),
        migrations.CreateModel(
            name="AssetTypeConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("asset_type_id", models.IntegerField(unique=True)),
                ("code_prefix", models.CharField(blank=True, max_length=12)),
                ("next_number", models.PositiveIntegerField(default=1)),
                (
                    "depreciation_method",
                    models.CharField(
                        choices=[
                            ("none", "No depreciation"),
                            ("straight_line", "Straight line"),
                            ("declining", "Declining balance"),
                        ],
                        default="straight_line",
                        max_length=20,
                    ),
                ),
                ("useful_life_months", models.PositiveIntegerField(default=36)),
                (
                    "salvage_percent",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=5
                    ),
                ),
                (
                    "maintenance_interval_days",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ClearanceWaiver",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("employee_id", models.IntegerField(db_index=True)),
                ("reason", models.TextField()),
                ("waived_by_id", models.IntegerField(blank=True, null=True)),
                ("waived_at", models.DateTimeField(auto_now_add=True)),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "permissions": (
                    (
                        "waive_assetclearance",
                        "Can release exit clearance with assets open",
                    ),
                ),
            },
        ),
        migrations.CreateModel(
            name="MaintenanceRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=30, unique=True)),
                ("asset_id", models.IntegerField(db_index=True)),
                ("schedule_id", models.IntegerField(blank=True, null=True)),
                ("damage_id", models.IntegerField(blank=True, null=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("preventive", "Preventive (scheduled)"),
                            ("breakdown", "Breakdown / repair"),
                            ("inspection", "Inspection"),
                        ],
                        default="breakdown",
                        max_length=12,
                    ),
                ),
                ("vendor", models.CharField(blank=True, max_length=150)),
                ("description", models.TextField()),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "cost",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "downtime_hours",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=10, null=True
                    ),
                ),
                (
                    "reading",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=12, null=True
                    ),
                ),
                (
                    "result",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "—"),
                            ("fixed", "Fixed"),
                            ("not_fixed", "Could not be fixed"),
                            ("replaced", "Part replaced"),
                            ("ok", "No fault found"),
                        ],
                        default="",
                        max_length=12,
                    ),
                ),
                ("result_notes", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "In maintenance"),
                            ("closed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="open",
                        max_length=10,
                    ),
                ),
                ("status_before", models.CharField(blank=True, max_length=20)),
                ("created_by_id", models.IntegerField(blank=True, null=True)),
                ("closed_by_id", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-start_date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="MaintenanceSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("asset_id", models.IntegerField(db_index=True)),
                ("title", models.CharField(max_length=150)),
                (
                    "interval_type",
                    models.CharField(
                        choices=[
                            ("days", "Days"),
                            ("km", "Kilometres"),
                            ("hours", "Running hours"),
                        ],
                        default="days",
                        max_length=8,
                    ),
                ),
                ("interval_value", models.PositiveIntegerField()),
                ("last_done_date", models.DateField(blank=True, null=True)),
                (
                    "last_done_reading",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=12, null=True
                    ),
                ),
                ("next_due_date", models.DateField(blank=True, null=True)),
                (
                    "next_due_reading",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=12, null=True
                    ),
                ),
                ("remind_days_before", models.PositiveIntegerField(default=7)),
                ("vendor", models.CharField(blank=True, max_length=150)),
                (
                    "estimated_cost",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("reminded_for", models.CharField(blank=True, max_length=40)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="RecoveryInstalment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_type", models.CharField(max_length=8)),
                ("source_id", models.IntegerField()),
                ("employee_id", models.IntegerField(db_index=True)),
                ("month", models.DateField(help_text="First day of the payroll month")),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "To be deducted"),
                            ("deducted", "Deducted in payroll"),
                            ("final_settlement", "In final settlement"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("payroll_run_id", models.IntegerField(blank=True, null=True)),
                ("payslip_id", models.IntegerField(blank=True, null=True)),
                ("done_on", models.DateField(blank=True, null=True)),
            ],
            options={
                "ordering": ["month", "id"],
            },
        ),
        migrations.CreateModel(
            name="SharedAllocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("asset_id", models.IntegerField(db_index=True)),
                (
                    "target_type",
                    models.CharField(
                        choices=[
                            ("location", "Location"),
                            ("department", "Department"),
                        ],
                        default="location",
                        max_length=12,
                    ),
                ),
                ("branch_id", models.IntegerField(blank=True, null=True)),
                ("location", models.CharField(blank=True, max_length=150)),
                ("department_id", models.IntegerField(blank=True, null=True)),
                (
                    "custodian_employee_id",
                    models.IntegerField(
                        blank=True,
                        help_text="Employee who looks after the shared asset",
                        null=True,
                    ),
                ),
                ("assigned_date", models.DateField()),
                ("expected_return_date", models.DateField(blank=True, null=True)),
                ("returned_date", models.DateField(blank=True, null=True)),
                ("return_condition", models.CharField(blank=True, max_length=20)),
                ("note", models.TextField(blank=True)),
                ("issued_by_id", models.IntegerField(blank=True, null=True)),
                ("transfer_id", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
