# Generated by Django 5.2.17 on 2026-10-07 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LeavePolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("code", models.CharField(max_length=30, unique=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("office", "Office staff"),
                            ("labour", "Labour / site staff"),
                            ("other", "Other"),
                        ],
                        default="office",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                (
                    "category_ids",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Employee categories that get this policy",
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="For employees whose category has no policy",
                    ),
                ),
                (
                    "leave_year_start",
                    models.PositiveSmallIntegerField(
                        default=1, help_text="Month the leave year starts (1 = January)"
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
                "permissions": (
                    ("run_leave_accrual", "Can run leave accrual and year end"),
                ),
            },
        ),
        migrations.CreateModel(
            name="LeaveLedger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("employee_id", models.IntegerField(db_index=True)),
                ("leave_type_id", models.IntegerField(db_index=True)),
                ("date", models.DateField(db_index=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("opening", "Opening balance"),
                            ("accrual", "Earned"),
                            ("taken", "Taken"),
                            ("cancelled", "Cancelled leave returned"),
                            ("encashed", "Encashed"),
                            ("carry_forward", "Carried forward"),
                            ("lapsed", "Lapsed"),
                            ("reset", "Yearly reset"),
                            ("adjustment", "Adjustment"),
                        ],
                        max_length=20,
                    ),
                ),
                ("days", models.FloatField()),
                ("ref_model", models.CharField(blank=True, default="", max_length=80)),
                ("ref_id", models.IntegerField(blank=True, null=True)),
                ("note", models.CharField(blank=True, default="", max_length=255)),
                ("created_by_id", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["date", "id"],
                "indexes": [
                    models.Index(
                        fields=["employee_id", "leave_type_id", "date"],
                        name="LeavePolicy_employe_3b8969_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="EmployeeLeavePolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("employee_id", models.IntegerField(unique=True)),
                ("note", models.CharField(blank=True, default="", max_length=200)),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employees",
                        to="LeavePolicy.leavepolicy",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LeavePolicyLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("leave_type_id", models.IntegerField()),
                ("days_per_year", models.FloatField(default=0)),
                (
                    "accrual",
                    models.CharField(
                        choices=[
                            ("monthly", "Monthly (earned each month)"),
                            (
                                "yearly",
                                "Yearly (full days at the start of the leave year)",
                            ),
                            (
                                "per_event",
                                "Per event (no balance, limits per request / year)",
                            ),
                            ("none", "No balance (unpaid / on request)"),
                        ],
                        default="monthly",
                        max_length=20,
                    ),
                ),
                (
                    "first_year_uae",
                    models.BooleanField(
                        default=False,
                        help_text="UAE annual leave: nothing in the first 6 months, then 2 days a month until 1 year",
                    ),
                ),
                (
                    "count_days",
                    models.CharField(
                        choices=[
                            ("calendar", "Calendar days"),
                            (
                                "working",
                                "Working days (no weekends or public holidays)",
                            ),
                        ],
                        default="calendar",
                        max_length=10,
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("B", "Both"), ("M", "Male"), ("F", "Female")],
                        default="B",
                        max_length=1,
                    ),
                ),
                ("min_service_months", models.PositiveIntegerField(default=0)),
                ("after_probation", models.BooleanField(default=False)),
                (
                    "notice_days",
                    models.PositiveIntegerField(
                        default=0, help_text="Days in advance the request must be made"
                    ),
                ),
                ("max_per_request", models.FloatField(blank=True, null=True)),
                ("max_per_year", models.FloatField(blank=True, null=True)),
                (
                    "max_times_in_service",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("requires_document", models.BooleanField(default=False)),
                ("allow_negative", models.BooleanField(default=False)),
                (
                    "pay_slabs",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="[[days, pay %], …] per leave year, e.g. [[15,100],[30,50],[45,0]]",
                    ),
                ),
                (
                    "carry_forward_max",
                    models.FloatField(
                        blank=True,
                        help_text="Days carried to the next leave year (empty = all)",
                        null=True,
                    ),
                ),
                (
                    "carry_forward_expiry_months",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "excess_action",
                    models.CharField(
                        choices=[
                            ("keep", "Keep (flag for HR)"),
                            ("encash", "Encash (request for approval)"),
                            ("lapse", "Lapse"),
                        ],
                        default="keep",
                        max_length=10,
                    ),
                ),
                ("encashable", models.BooleanField(default=False)),
                ("encash_max_per_year", models.FloatField(blank=True, null=True)),
                (
                    "law_reference",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="LeavePolicy.leavepolicy",
                    ),
                ),
            ],
            options={
                "ordering": ["policy", "id"],
                "unique_together": {("policy", "leave_type_id")},
            },
        ),
    ]
