# Generated by Django 5.2.17 on 2026-10-07 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LeavePolicy", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApprovalClock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("approval_id", models.IntegerField(unique=True)),
                ("started_at", models.DateTimeField()),
                ("escalated_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="LevelRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level_id",
                    models.IntegerField(
                        help_text="calendars.LeaveApprovalLevels id", unique=True
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("user", "Named user"),
                            ("reporting_manager", "Reporting manager"),
                            ("manager_of_manager", "Reporting manager's manager"),
                            ("branch_hr", "Branch HR manager"),
                            ("department_head", "Department head"),
                            ("company_hr", "Company HR manager"),
                        ],
                        default="user",
                        max_length=20,
                    ),
                ),
                (
                    "escalate_role",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("user", "Named user"),
                            ("reporting_manager", "Reporting manager"),
                            ("manager_of_manager", "Reporting manager's manager"),
                            ("branch_hr", "Branch HR manager"),
                            ("department_head", "Department head"),
                            ("company_hr", "Company HR manager"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="leavepolicyline",
            name="comp_expiry_days",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Compensatory off: days to use it before it lapses",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="leavepolicyline",
            name="comp_full_day_hours",
            field=models.FloatField(
                blank=True,
                help_text="Compensatory off: hours worked on a weekend / holiday for 1 day",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="leavepolicyline",
            name="comp_half_day_hours",
            field=models.FloatField(
                blank=True,
                help_text="Compensatory off: hours for half a day",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="leavepolicyline",
            name="prorate",
            field=models.CharField(
                choices=[
                    ("none", "No prorate (full amount)"),
                    ("calendar", "Calendar days of the month"),
                    ("fixed", "Fixed days a month (e.g. 30)"),
                ],
                default="calendar",
                help_text="Part month / part year on joining and leaving (and unpaid leave when switched on)",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="leavepolicyline",
            name="prorate_fixed_days",
            field=models.PositiveSmallIntegerField(
                default=30, help_text="Days in a month for the fixed-days method"
            ),
        ),
        migrations.AddField(
            model_name="leavepolicyline",
            name="prorate_unpaid",
            field=models.BooleanField(
                default=False,
                help_text="Unpaid leave days in a month reduce what is earned",
            ),
        ),
        migrations.AlterField(
            model_name="leavepolicyline",
            name="accrual",
            field=models.CharField(
                choices=[
                    ("monthly", "Monthly (earned each month)"),
                    ("yearly", "Yearly (full days at the start of the leave year)"),
                    ("per_event", "Per event (no balance, limits per request / year)"),
                    ("none", "No balance (unpaid / on request)"),
                    ("earned", "Earned by work (compensatory off)"),
                ],
                default="monthly",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="OrgRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("branch_hr", "Branch HR manager"),
                            ("department_head", "Department head"),
                            ("company_hr", "Company HR manager"),
                        ],
                        max_length=20,
                    ),
                ),
                ("branch_id", models.IntegerField(blank=True, null=True)),
                ("department_id", models.IntegerField(blank=True, null=True)),
                ("user_id", models.IntegerField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "unique_together": {("role", "branch_id", "department_id")},
            },
        ),
    ]
