# Generated by Django 5.2.17 on 2026-10-07 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LeavePolicy", "0002_v1_11_0"),
    ]

    operations = [
        migrations.AddField(
            model_name="leavepolicyline",
            name="service_steps",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='Days by length of service: [{"from_year": 3, "days": 26, "carry_forward_max": null}, …]. Service year 1 (and any year before the first step) uses days_per_year.',
            ),
        ),
        migrations.AddField(
            model_name="leavepolicyline",
            name="worked_paid_leave",
            field=models.BooleanField(
                default=True,
                help_text="Days worked prorate: paid leave days count as days worked",
            ),
        ),
        migrations.AddField(
            model_name="leavepolicyline",
            name="worked_source",
            field=models.CharField(
                choices=[
                    ("punch", "Check-ins (attendance records)"),
                    ("calendar", "Attendance calendar (Present days)"),
                ],
                default="punch",
                help_text="Days worked prorate: where the days worked come from",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="leavepolicyline",
            name="prorate",
            field=models.CharField(
                choices=[
                    ("none", "No prorate (full amount)"),
                    ("calendar", "Calendar days of the month"),
                    ("fixed", "Fixed days a month (e.g. 30)"),
                    ("worked", "Days worked (attendance)"),
                ],
                default="calendar",
                help_text="Part month / part year on joining and leaving (and unpaid leave when switched on)",
                max_length=10,
            ),
        ),
    ]
