# Generated by Django 5.2.17 on 2026-10-08 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Grievance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=30
                    ),
                ),
                ("employee_id", models.IntegerField(db_index=True)),
                (
                    "branch_id",
                    models.IntegerField(blank=True, db_index=True, null=True),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("harassment", "Harassment"),
                            ("pay", "Pay"),
                            ("workplace", "Workplace"),
                            ("manager", "Manager"),
                            ("safety", "Safety"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("subject", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "against",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="person or area concerned (optional)",
                        max_length=200,
                    ),
                ),
                ("incident_date", models.DateField(blank=True, null=True)),
                ("confidential", models.BooleanField(default=True)),
                ("anonymous", models.BooleanField(default=False)),
                (
                    "token_hash",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=64
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("submitted", "Submitted"),
                            ("acknowledged", "Acknowledged"),
                            ("investigating", "Investigating"),
                            ("resolved", "Resolved"),
                            ("closed", "Closed"),
                        ],
                        db_index=True,
                        default="submitted",
                        max_length=15,
                    ),
                ),
                ("assigned_user_ids", models.JSONField(blank=True, default=list)),
                ("sla_days", models.PositiveIntegerField(default=10)),
                ("due_date", models.DateField(blank=True, null=True)),
                ("escalated", models.BooleanField(default=False)),
                ("escalation_level", models.PositiveIntegerField(default=0)),
                ("escalated_at", models.DateTimeField(blank=True, null=True)),
                ("outcome", models.TextField(blank=True, default="")),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "feedback_rating",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "feedback_text",
                    models.CharField(blank=True, default="", max_length=1000),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "permissions": [
                    ("handle_grievance", "Can handle employee complaints / grievances")
                ],
            },
        ),
        migrations.CreateModel(
            name="GrievanceSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("harassment", "Harassment"),
                            ("pay", "Pay"),
                            ("workplace", "Workplace"),
                            ("manager", "Manager"),
                            ("safety", "Safety"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("sla_days", models.PositiveIntegerField(default=10)),
                ("acknowledge_days", models.PositiveIntegerField(default=2)),
                ("officer_user_ids", models.JSONField(blank=True, default=list)),
                ("escalate_to_user_ids", models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.CreateModel(
            name="LetterRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=30
                    ),
                ),
                ("employee_id", models.IntegerField(db_index=True)),
                (
                    "branch_id",
                    models.IntegerField(blank=True, db_index=True, null=True),
                ),
                (
                    "letter_type",
                    models.CharField(
                        choices=[
                            ("salary_certificate", "Salary certificate"),
                            ("salary_transfer", "Salary transfer letter (to bank)"),
                            ("noc_travel", "NOC – travel"),
                            ("noc_visa", "NOC – visa"),
                            ("noc_other", "NOC – other"),
                            ("experience", "Experience certificate"),
                            ("employment", "Employment certificate"),
                            ("embassy", "Embassy letter"),
                            ("bank_account", "Bank account opening letter"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("en", "English"), ("ar", "Arabic")],
                        default="en",
                        max_length=2,
                    ),
                ),
                ("addressee", models.CharField(blank=True, default="", max_length=300)),
                ("purpose", models.CharField(blank=True, default="", max_length=500)),
                ("bank_name", models.CharField(blank=True, default="", max_length=150)),
                ("travel_from", models.DateField(blank=True, null=True)),
                ("travel_to", models.DateField(blank=True, null=True)),
                (
                    "destination",
                    models.CharField(blank=True, default="", max_length=150),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Waiting for HR"),
                            ("issued", "Ready to download"),
                            ("rejected", "Rejected"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=12,
                    ),
                ),
                ("issued_directly", models.BooleanField(default=False)),
                (
                    "reference_no",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=40
                    ),
                ),
                (
                    "verification_code",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=20
                    ),
                ),
                (
                    "pdf",
                    models.FileField(blank=True, null=True, upload_to="ess/letters/"),
                ),
                ("body_snapshot", models.TextField(blank=True, default="")),
                ("decided_by_id", models.IntegerField(blank=True, null=True)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                (
                    "decision_note",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("created_by_id", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="ProfileChangeRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=30
                    ),
                ),
                ("employee_id", models.IntegerField(db_index=True)),
                (
                    "branch_id",
                    models.IntegerField(blank=True, db_index=True, null=True),
                ),
                ("group", models.CharField(max_length=40)),
                ("record_id", models.IntegerField(blank=True, null=True)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Add"),
                            ("update", "Change"),
                            ("delete", "Remove"),
                        ],
                        default="update",
                        max_length=10,
                    ),
                ),
                ("old_values", models.JSONField(blank=True, default=dict)),
                ("new_values", models.JSONField(blank=True, default=dict)),
                ("reason", models.CharField(blank=True, default="", max_length=500)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Waiting for HR"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("withdrawn", "Withdrawn"),
                            ("failed", "Approved – could not be applied"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=12,
                    ),
                ),
                ("decided_by_id", models.IntegerField(blank=True, null=True)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                (
                    "decision_note",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("applied_at", models.DateTimeField(blank=True, null=True)),
                ("applied_record_id", models.IntegerField(blank=True, null=True)),
                ("error", models.JSONField(blank=True, default=dict)),
                ("created_by_id", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="EssFieldPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("group", models.CharField(max_length=40)),
                ("field", models.CharField(blank=True, default="", max_length=80)),
                (
                    "policy",
                    models.CharField(
                        choices=[
                            ("self", "Employee changes it directly"),
                            ("request", "Employee requests – HR approves"),
                            ("hr", "HR only (shown read-only)"),
                            ("hidden", "Not shown in self service"),
                        ],
                        max_length=10,
                    ),
                ),
                ("updated_by_id", models.IntegerField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["group", "field"],
                "unique_together": {("group", "field")},
            },
        ),
        migrations.CreateModel(
            name="GrievanceMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("author_user_id", models.IntegerField(blank=True, null=True)),
                ("from_employee", models.BooleanField(default=False)),
                (
                    "internal",
                    models.BooleanField(
                        default=False,
                        help_text="note between handlers, never shown to the employee",
                    ),
                ),
                ("text", models.TextField(blank=True, default="")),
                (
                    "attachment",
                    models.FileField(
                        blank=True, null=True, upload_to="ess/grievances/"
                    ),
                ),
                ("event", models.CharField(blank=True, default="", max_length=30)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "grievance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="SelfService.grievance",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="LetterTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "letter_type",
                    models.CharField(
                        choices=[
                            ("salary_certificate", "Salary certificate"),
                            ("salary_transfer", "Salary transfer letter (to bank)"),
                            ("noc_travel", "NOC – travel"),
                            ("noc_visa", "NOC – visa"),
                            ("noc_other", "NOC – other"),
                            ("experience", "Experience certificate"),
                            ("employment", "Employment certificate"),
                            ("embassy", "Embassy letter"),
                            ("bank_account", "Bank account opening letter"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("en", "English"), ("ar", "Arabic")],
                        default="en",
                        max_length=2,
                    ),
                ),
                (
                    "branch_id",
                    models.IntegerField(
                        blank=True, help_text="empty = all branches", null=True
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "body",
                    models.TextField(
                        help_text="Text with placeholders such as {employee_name}, {designation}, {basic_salary}"
                    ),
                ),
                ("footer", models.CharField(blank=True, default="", max_length=300)),
                (
                    "signatory_name",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "signatory_title",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("show_salary", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("updated_by_id", models.IntegerField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["letter_type", "language"],
                "unique_together": {("letter_type", "language", "branch_id")},
            },
        ),
        migrations.CreateModel(
            name="ChangeRequestAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="ess/change_requests/")),
                ("name", models.CharField(blank=True, default="", max_length=200)),
                ("uploaded_by_id", models.IntegerField(blank=True, null=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="SelfService.profilechangerequest",
                    ),
                ),
            ],
        ),
    ]
