# Generated by Django 5.2.17 on 2026-10-06 09:28

import LearningManagement.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("EmpManagement", "0002_initial"),
        ("OrganisationManager", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(blank=True, max_length=30, unique=True)),
                ("title", models.CharField(max_length=200)),
                (
                    "provider",
                    models.CharField(
                        blank=True,
                        help_text="Leave empty for internal courses",
                        max_length=150,
                        null=True,
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("internal_classroom", "Internal - classroom"),
                            ("internal_elearning", "Internal - e-learning"),
                            ("external_classroom", "External - classroom"),
                            ("external_online", "External - online"),
                        ],
                        default="internal_classroom",
                        max_length=30,
                    ),
                ),
                (
                    "duration_hours",
                    models.DecimalField(decimal_places=1, default=8, max_digits=6),
                ),
                (
                    "target_audience",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "course_type",
                    models.CharField(
                        choices=[
                            ("mandatory", "Mandatory (all staff)"),
                            ("mandatory_role", "Mandatory (role)"),
                            ("optional", "Optional"),
                        ],
                        default="optional",
                        max_length=20,
                    ),
                ),
                (
                    "cost_per_head",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("pass_mark", models.PositiveSmallIntegerField(default=70)),
                (
                    "certificate_validity_months",
                    models.PositiveSmallIntegerField(
                        blank=True, help_text="Empty = no expiry", null=True
                    ),
                ),
                ("objectives", models.TextField(blank=True, null=True)),
                (
                    "content_file",
                    models.FileField(
                        blank=True, null=True, upload_to="learning/content/"
                    ),
                ),
                ("content_link", models.URLField(blank=True, null=True)),
                ("auto_assign_new_joiners", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "departments",
                    models.ManyToManyField(
                        blank=True,
                        related_name="courses",
                        to="OrganisationManager.dept_master",
                    ),
                ),
            ],
            options={
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Nomination",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nominated_by",
                    models.CharField(
                        choices=[
                            ("manager", "Manager"),
                            ("self", "Self"),
                            ("hr", "HR / L&D"),
                            ("auto", "Automatic"),
                        ],
                        default="manager",
                        max_length=10,
                    ),
                ),
                ("reason", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "manager_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                (
                    "ld_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                (
                    "seat_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("waitlist", "Waitlist"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                (
                    "rejection_reason",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("bond_required", models.BooleanField(default=False)),
                ("bond_accepted_on", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="training_nominations",
                        to="EmpManagement.emp_master",
                    ),
                ),
            ],
            options={
                "ordering": ["session", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="ParticipantResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("attended", models.BooleanField(default=True)),
                ("attendance_percent", models.PositiveSmallIntegerField(default=100)),
                (
                    "pre_test_score",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "post_test_score",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("passed", models.BooleanField(blank=True, null=True)),
                (
                    "feedback_rating",
                    models.PositiveSmallIntegerField(
                        blank=True, help_text="1-5", null=True
                    ),
                ),
                (
                    "trainer_rating",
                    models.PositiveSmallIntegerField(
                        blank=True, help_text="1-5", null=True
                    ),
                ),
                ("feedback_comment", models.TextField(blank=True, null=True)),
                (
                    "nomination",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="result",
                        to="LearningManagement.nomination",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TrainingNeed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("need", models.CharField(max_length=255)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("appraisal", "Appraisal"),
                            ("pip", "PIP"),
                            ("manager", "Manager request"),
                            ("self", "Self request"),
                            ("new_joiner", "New joiner"),
                            ("compliance", "Compliance / expiry"),
                            ("hr", "HR"),
                        ],
                        default="manager",
                        max_length=20,
                    ),
                ),
                (
                    "source_reference",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                            ("mandatory", "Mandatory"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("identified", "Identified"),
                            ("pending_approval", "Pending approval"),
                            ("planned", "Planned"),
                            ("nominated", "Nominated"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="identified",
                        max_length=20,
                    ),
                ),
                ("target_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="needs",
                        to="LearningManagement.course",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="training_needs",
                        to="EmpManagement.emp_master",
                    ),
                ),
            ],
            options={
                "ordering": ["status", "-created_at"],
            },
        ),
        migrations.AddField(
            model_name="nomination",
            name="need",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="nominations",
                to="LearningManagement.trainingneed",
            ),
        ),
        migrations.CreateModel(
            name="TrainingSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(blank=True, max_length=30, unique=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("start_time", models.TimeField(blank=True, null=True)),
                ("end_time", models.TimeField(blank=True, null=True)),
                (
                    "trainer_external",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("venue", models.CharField(blank=True, max_length=150, null=True)),
                ("online_link", models.URLField(blank=True, null=True)),
                ("seats", models.PositiveIntegerField(default=20)),
                (
                    "cost_per_head",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Empty = course cost",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("nomination_deadline", models.DateField(blank=True, null=True)),
                (
                    "bond_threshold",
                    models.DecimalField(
                        decimal_places=2,
                        default=1000,
                        help_text="Training bond needed when cost per head is above this",
                        max_digits=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("in_progress", "In progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sessions",
                        to="LearningManagement.course",
                    ),
                ),
                (
                    "trainer_employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sessions_trained",
                        to="EmpManagement.emp_master",
                    ),
                ),
            ],
            options={
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="TrainingBond",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("start_date", models.DateField(default=django.utils.timezone.now)),
                (
                    "schedule",
                    models.JSONField(
                        default=LearningManagement.models.default_bond_schedule,
                        help_text='[{"months": 12, "percent": 100}, ...] - leaving within N months repays percent',
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending acceptance"),
                            ("active", "Active"),
                            ("completed", "Completed (served)"),
                            ("recovered", "Recovered"),
                            ("waived", "Waived"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("accepted_on", models.DateTimeField(blank=True, null=True)),
                (
                    "recovered_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("notes", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bonds",
                        to="LearningManagement.course",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="training_bonds",
                        to="EmpManagement.emp_master",
                    ),
                ),
                (
                    "nomination",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bond",
                        to="LearningManagement.nomination",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bonds",
                        to="LearningManagement.trainingsession",
                    ),
                ),
            ],
            options={
                "ordering": ["-start_date"],
            },
        ),
        migrations.AddField(
            model_name="nomination",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="nominations",
                to="LearningManagement.trainingsession",
            ),
        ),
        migrations.CreateModel(
            name="Certificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "certificate_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("issued_by", models.CharField(blank=True, max_length=150, null=True)),
                ("issued_on", models.DateField(default=django.utils.timezone.now)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                (
                    "file",
                    models.FileField(
                        blank=True, null=True, upload_to="learning/certificates/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="training_certificates",
                        to="EmpManagement.emp_master",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="certificates",
                        to="LearningManagement.course",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="certificates",
                        to="LearningManagement.trainingsession",
                    ),
                ),
            ],
            options={
                "ordering": ["expiry_date", "-issued_on"],
            },
        ),
        migrations.AlterUniqueTogether(
            name="nomination",
            unique_together={("session", "employee")},
        ),
    ]
